### ISSUE TITLE
Remove lines from notification section of settings menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#122]
Since the number of notifications and do not disturb function are both part of the settings functionality, please remove the lines where I have marked in yellow.  We should only partition when concepts change. This will allow us to save some space on this screen. 

![image](https://user-images.githubusercontent.com/59370537/81565570-8cb7ed00-9367-11ea-82d0-7e0367d7b751.png)

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 18th release, 
please reopen it if the functionality not working as expected.
