### ISSUE TITLE
Eliminate space at top of settings menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#123]
There is a large amount of space at the top of the settings menu which we should reduce (marked in yellow). This will allow most phones to see the T&C rather than it being cut off or not at all visible on smaller screens. 

![image](https://user-images.githubusercontent.com/59370537/81565931-1ff12280-9368-11ea-9746-bc123f97c794.png)

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the may 18th release, 
please reopen it if the functionality not working as expected.
