### ISSUE TITLE
App icon when scrolling through apps 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#166]
The app icon does not display when scrolling through apps.  Makes it difficult to quickly spot the app when trying to return to it from another. 

![image](https://user-images.githubusercontent.com/59370537/84700761-c4472580-af21-11ea-9ab4-a910cff30ada.png)

**Comment by AJBouzidi** [comment]
@mullhol could you restart your phone? is it the first time happen?

**Comment by mullhol** [comment]
No longer appears to be an issue
