### ISSUE TITLE
Canada banner on login page

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#174]
Could we add the Canada banner to bottom of the login screen, so it mirrors the splash screen? 

![image](https://user-images.githubusercontent.com/59370537/86611170-47392a00-bf7c-11ea-89a9-1a3b58902d95.png)

**Comment by Jiandong-Guo** [comment]
fixed, will see in next release

**Comment by mullhol** [comment]
This has been resolved
