### ISSUE TITLE
Return banner in results menu

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#175]
The return banner in the results menu should be the same thickness as the return banner in other app menus. Currently, the return banner in the results menu is too thin and causes the return button to border right on the edge of the screen. Attached iphone 11 screen shots to show the difference.

![image](https://user-images.githubusercontent.com/59370537/87164670-0bada100-c297-11ea-853f-db74f0b1f9ab.png)
![image](https://user-images.githubusercontent.com/59370537/87164715-1b2cea00-c297-11ea-95eb-fd84544e93b1.png)

**Comment by Jiandong-Guo** [comment]
Fixed and will be seen in next release

**Comment by mullhol** [comment]
Confirmed implemented.
