### ISSUE TITLE
Portion of results screens where swipe does not work 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#176]
There is a large portion of the each results screen which doesn't allow me to swipe.  The swipe works perfectly if I swipe close to or on the graphics, but if I try to swipe in the areas I highlighted in yellow on the screen shots below, it doesn't work. 

![image](https://user-images.githubusercontent.com/59370537/87165425-216f9600-c298-11ea-878e-a40c085ef8ed.png)

![image](https://user-images.githubusercontent.com/59370537/87165460-2f251b80-c298-11ea-9954-5c62a20e66ee.png)

**Comment by Jiandong-Guo** [comment]
From my iphone 11 simulator, I don't see the empty area in the bottom.
any way, I added more code to fix the swipe problem, please test in next release

**Comment by mullhol** [comment]
@Jiandong-Guo I still can't swipe in those areas, only on the image itself.

**Comment by Jiandong-Guo** [comment]
@mullhol ,Please notice the red rectangle area that is swipe-able area, please notice if there is a big gap between the bottom of red rectangle and the top edge of the return bar or bottom of the device screen

**Comment by mullhol** [comment]
The revisions look great, and the red rectangle is well placed on both iphone 11 (large screen) and iphone 6s (small screen). @Jiandong-Guo You can remove the red rectangle.
