### ISSUE TITLE
Update app icon/logo

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#177]
Please update the app's icon/logo to the newly designed version from COMM.  

![WellnessCheckLogo-576x576](https://user-images.githubusercontent.com/59370537/88184594-e73fb600-cc00-11ea-9ad5-0ba03f557feb.png)
![WellnessCheckLogo1024x1024](https://user-images.githubusercontent.com/59370537/88184598-e870e300-cc00-11ea-81f5-f8256f76c961.png)

![WellnessCheckLogo](https://user-images.githubusercontent.com/59370537/88185261-bad86980-cc01-11ea-9520-48c3b3a430dd.png)
![WellnessCheckLogo-B W](https://user-images.githubusercontent.com/59370537/88185266-bb710000-cc01-11ea-9776-7981492c4654.png)

**Comment by Jiandong-Guo** [comment]
Fixed, Please test it in next release

**Comment by mullhol** [comment]
@Jiandong-Guo It looks great!  Let's just revise the size of the logo on the splash page and login page, so it's closer in width to the name of the app.  For example....

![image](https://user-images.githubusercontent.com/59370537/88567104-037a9300-d005-11ea-9c65-8f22edb2ed92.png)

**Comment by mullhol** [comment]
@Jiandong-Guo Could you put the pink background on the phone homepage version as well? 

![image](https://user-images.githubusercontent.com/59370537/88574464-60c81180-d010-11ea-8219-47572f90b556.png)

**Comment by Jiandong-Guo** [comment]
1) the space(10 pixels) between the icon and title label was removed, Please check if it is close enough.
2) What's your meaning "phone homepage" ?  do you mean the icon on phone device desktop ?
3) If yes, I can add background color to it the question is that do you want to add a simple pink color to its background? because the image above has a ocean wave background. if you need the complex image other than simple color as background, please give me that image such as the ocean wave image in above image. 
3)

**Comment by mullhol** [comment]
1) Spacing looks good now! 
2) Yes, on the phone device desktop
3) I want the pink used in the background of the previous icon. The ocean wave is my phone's desktop - you can ignore that.

**Comment by Jiandong-Guo** [comment]
![image](https://user-images.githubusercontent.com/58485300/88697564-c4b30e80-d0d2-11ea-89f6-052bca2a9b34.png)


This is image1 which keeps original background in the center

![image](https://user-images.githubusercontent.com/58485300/88697753-1a87b680-d0d3-11ea-81b2-799258f53921.png)
This is image2 whick changes all background

Please choose which one is better? @mullhol

**Comment by mullhol** [comment]
@Jiandong-Guo The second one, as that will align with how it's displayed in the app.  Thank you!

**Comment by Jiandong-Guo** [comment]
Fixed and please test it

**Comment by mullhol** [comment]
@Jiandong-Guo The only revision missing is to make the graphic larger on the splash page and the login page. You can use this image as a guide for approximately how large it should be.l 

![image](https://user-images.githubusercontent.com/59370537/89414328-36eda980-d6f8-11ea-8acb-83a30126597f.png)

**Comment by Jiandong-Guo** [comment]
Changed ftom 128*128 to 200*200, Please test it in next release

**Comment by Jiandong-Guo** [comment]
typo:  128*128  to 200*200

**Comment by mullhol** [comment]
@Jiandong-Guo The size on the splash page and login screen is perfect, but I'd like the image to be a little more crisp. Please let me know what needs to be procured from COMM to make this happen and I will request it. 

cc @AJBouzidi

**Comment by AJBouzidi** [comment]
@mullhol I think the color inside the logo been added using paint after the logo been created that's why you see a white color on the edges. If COMM can create the logo and add the color without us editing it will be great. (576X576)
![LogoColor](https://user-images.githubusercontent.com/58231743/90542156-b005eb80-e151-11ea-9c20-dde445fe2653.PNG)

**Comment by mullhol** [comment]
@AJBouzidi I'm not seeing white around the edges, the edges are pixelated.  Also, the background of the splash screen and password page are not solid colour, so we would not be able to have COMM add the colour unless they merged the logo with the background.  I just need to know what size/resolution you need to make the graphic the size Jiandong has scaled it to, but more clean and crisp. 

cc @Jiandong-Guo

**Comment by AJBouzidi** [comment]
Logo has been changed to one with a much better resolution.
This is will be in the next release.

**Comment by mullhol** [comment]
New resolution looks much better. Thanks guys!
