### ISSUE TITLE
spinner staying on dashboard screens 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#178]
When I access the dashboard after completing a survey, the spinner doesn't leave the screen.  Tested it for 2 minutes. 

![image](https://user-images.githubusercontent.com/59370537/88200219-de0c1480-cc13-11ea-8ad8-5510773aee9c.png)

**Comment by Jiandong-Guo** [comment]
It happens due to the network or server problem not to be able to finish downloading 8 graph images.
I added max 10 seconds to let the spinner to live.  Please test again.
