### ISSUE TITLE
Android Testing - issues with scrolling in Info menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#179]
Trish is testing on Samsung S9 Plus - Android 10 and has reported the following issue: 
There seems to be a lag when I'm trying to scroll down the screen of the information menu. Then when I get to the bottom of the screen, I have trouble scrolling back up. I have to try a few times to move/scroll upwards.

I tested this in iphone this morning, it's working well.  Seems Android specific.

**Comment by Jiandong-Guo** [comment]
Fixed, Please test it in next release

**Comment by mullhol** [comment]
Successfully implemented
