### ISSUE TITLE
digit missing in Android timepicker

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#181]
There is a digit missing in the minutes of the "do not disturb after" option. 

![image](https://user-images.githubusercontent.com/59370537/88304032-b9787100-ccd5-11ea-9984-9f35feb3bb23.png)

**Comment by Jiandong-Guo** [comment]
Fixed, Please test it in next release

**Comment by mullhol** [comment]
Successfully implemented
