### ISSUE TITLE
Logic for randomization of results menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#183]
@Jiandong-Guo Amanda and I are testing the randomization of the results menu.  Would you be able to provide the logic so she can review against her assumptions? 

From Amanda: "My only concern is that it SEEMED like each time there was a tie, the one that was most recently recorded was not displayed. My sample size was only 3 different scenarios so of course it is possible that each time the last one was randomly discarded correctly but just wanted to verify with Jiandong that this is the case and ensure it’s not coded systematically?"

**Comment by Jiandong-Guo** [comment]
Will send you an email to explain it.

**Comment by mullhol** [comment]
Amanda is reviewing the logic. Will close or update ticket once this is complete.

**Comment by mullhol** [comment]
@Jiandong-Guo Methodology is asking if the tie can be fully randomized instead of selecting the first in the tag? 


From Amanda: 

From the logic "Those 3  have same numberSelected=1, they are tie. We have to choose one from these 3.  They are sorted by the occurrence sequence, The “Home” is the first in the tag, so the “Home” will be selected."

Ideally, we want those that have the same number selected in this case to all have an equal chance of being displayed. So for that specific example, we’d like one of the 3 to be randomly selected (home, away for business or library/museum/theatre) to be displayed and not always the first one in the order sequence.

**Comment by Jiandong-Guo** [comment]
Ok,  Will add another random pick function among "ties" in next release

**Comment by mullhol** [comment]
Methodology has tested and confirm the randomization is working perfectly.
