### ISSUE TITLE
Revise info in Results menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#184]
Can you please revise the "i" icon in the Results menu to a question mark icon, and replace the existing content with the following: 

All questions about feelings are based on a scale of 0 meaning ‘not at all’, and 10 meaning ’completely’. Based on this, a high rating of feeling happy compared to a high rating of feeling anxious would be interpreted quite differently.

These results are reported in real time and have not been validated by Statistics Canada. Caution should be exercised when interpreting the data.

Toutes les questions relatives aux sentiments sont évaluées sur une échelle de 0 à 10, où 0 signifie « pas du tout » et 10 signifie « complètement ». En fonction de cette échelle, une cote élevée de sentiment de bonheur par rapport à une cote élevée de sentiment d’anxiété serait interprétée de manière très différente.

Ces résultats sont communiqués en temps réel et n’ont pas été validés par Statistique Canada. Il convient d’être prudent lors de l’interprétation des données.

**Comment by Jiandong-Guo** [comment]
Fixed and please test it

**Comment by mullhol** [comment]
Successfully implemented
