### ISSUE TITLE
Revision to FAQ content 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#185]
We previously revised the FAQ content for the Results menu based on the assumption the 0 would be removed from the scale. As the 0 is staying, we need to correct the FAQ content to revise mentions of 1 to 0. We also need to change the word "very" to "completely" to align with the questionnaire. Please see image below for yellow highlight of changes. 

![image](https://user-images.githubusercontent.com/59370537/88947925-3fa93000-d25f-11ea-8e29-8a77fd4664d1.png)

**Comment by mullhol** [comment]
@Jiandong-Guo ticket updated to include revision of the word "very"

**Comment by Jiandong-Guo** [comment]
Fixed and please test it

**Comment by mullhol** [comment]
Successfully implemented
