### ISSUE TITLE
Spacing in password verification menu 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#186]
When using the help button option for password verification, the lines are spaced the same when they all meet the criteria, or fail all the criteria. If there is a combination of meeting and failing the criteria, they are not properly spaced (see special character and lowercase in the screen shot below). Can we correct this so they are always double spaced from each other? 

![image](https://user-images.githubusercontent.com/59370537/89415208-8d0f1c80-d6f9-11ea-87cc-645d837da983.png)

**Comment by Jiandong-Guo** [comment]
Fixed, Please test it in next release

**Comment by mullhol** [comment]
confirmed implemented
