### ISSUE TITLE
New tester accounts 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#187]
Please include Matthew and Rachel in the list of testers moving forward.  Here is the required info: 

Device: Android
Mode: Samsung S6
Operating System: Android 7.0
E-mail used in GooglePlay: mlymburner@gmail.com

Type: Android
Model: Pixel 3
OS: Android 10
Email: rachel.leistra2@gmail.com

**Comment by Jiandong-Guo** [comment]
@AJBouzidi 
Seems the google play console cannot append new users, if put these 2 email in a csv file and upload, it will replace the old list, do you still have the old email list ?

**Comment by AJBouzidi** [comment]
@Jiandong-Guo Google console is special, you just need to enter the email in the text box and hit Enter key. (I added them)
please add the 2 users in the release mail list.
