### ISSUE TITLE
multiple time out messages

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#188]
I leave the app and browse other apps until WBC times out. I go back to WBC, see the time out message, but go back to other apps rather than taking an action. When I go back to WBC, I get a second time out message and have to clear both it and the original one.  Is there a way to only have one time out message?

**Comment by Jiandong-Guo** [comment]
@AJBouzidi It was fixed and please test in ios first,then test in next release

**Comment by AJBouzidi** [comment]
@Jiandong-Guo this is has been tested on the simulators and it's working fine.

**Comment by mullhol** [comment]
confirmed implemented
