### ISSUE TITLE
Revision to change password flow 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#189]
When landing on the login page I selected "forgot password". 
I answered my security question and clicked "next". 
On the enter new password page, I realize I remember my password and select "cancel". 

The cancel button took me back to the answer my security question screen, but it should logically go back to the login screen.  There would be no reason to return to the answer my security question screen, as I obviously did that correctly in order to reach the enter new password screen.  Can we correct this flow?

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the next release.

**Comment by mullhol** [comment]
Reopening until tested

**Comment by Jiandong-Guo** [comment]
Fixed and please test in next release

**Comment by mullhol** [comment]
Confirmed implemented
