### ISSUE TITLE
Revision to FAQ

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#190]
Please revise question header : 
What does the Results menu tell me? How can I interpret my results? / Que me dit le menu Résultats? Comment puis-je interpréter mes résultats?

To: 
What does the Results menu tell me? / Que me dit le menu Résultats?

**Comment by AJBouzidi** [comment]
This is done will be in the next release.

**Comment by mullhol** [comment]
@AJBouzidi We revised the procedure - once the work is complete, reassign the ticket to me, and I will close it when I confirm the work has been done. It makes it easier for me to keep track and confirm work quickly.

**Comment by mullhol** [comment]
Confirmed implemented
