### ISSUE TITLE
Correction in FAQ

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#192]
The phone number in the FAQ should be tappable.  
This needs to be corrected in the Technical Difficulties section, for the following two FAQ: 

1. I cannot access the questionnaires or my results
2. I am experiencing other technical difficulties 

This needs to be revised in both the English and French versions.

**Comment by AJBouzidi** [comment]
@mullhol it's working on the Ipad and on the Simulator.
Could you test also:
Category: Settings and notifications 
Question: Why am I no longer receiving notification?
![IMG_0169](https://user-images.githubusercontent.com/58231743/89940920-484b2000-dbe8-11ea-92d4-1936faf2053e.PNG)

**Comment by mullhol** [comment]
@AJBouzidi  None of the three are working on iPhone 11.

**Comment by mullhol** [comment]
@AJBouzidi I can tap on the phone numbers now, but it's very difficult. I seem to need to tap 5-6 times before I can get the right spot to open the call feature. Is there anything we can do to make this easier?

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the next release.

**Comment by mullhol** [comment]
New boundaries make the tap much easier. Issue resolved.
