### ISSUE TITLE
revision to applicable law in T&C 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#193]
Please remove the word disclaimer from the applicable law section of the English version of the Terms and Conditions. 

Current content: 

Disclaimer This App and its Terms and Conditions are governed by the laws of the province of Ontario and Applicable laws of Canada. Legal proceedings related to this App and its Terms and Conditions may only be brought in the courts of Ontario or the Federal Court of Canada.

Requested content: 

This App and its Terms and Conditions are governed by the laws of the province of Ontario and Applicable laws of Canada. Legal proceedings related to this App and its Terms and Conditions may only be brought in the courts of Ontario or the Federal Court of Canada.

**Comment by AJBouzidi** [comment]
Done, will be in the next release.

**Comment by mullhol** [comment]
confirmed implemented
