### ISSUE TITLE
Remove links from Terms and Conditions 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#194]
OPMIC has identified the links in the Terms and Conditions were for reference in translation only, not to be included in the actual published content. COMM has agreed to the removal of the links. 

Could we please remove the links from the following sections in the terms and conditions: 
General terms and conditions / Conditions générales
Privacy notice / Avis de confidentialité
Official language notice / Langues officielles
Accessibility notice / Avis de l’accessibilité
Trademark notice / Avis concernant l'image de marque

**Comment by AJBouzidi** [comment]
This is has been done and will be in the next release.

**Comment by mullhol** [comment]
confirmed implemented
