### ISSUE TITLE
Deletion of password entry 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#196]
When setting a password, I typed half of the password I wanted to use then clicked "?" to verify the requirements. When I exited the requirements window, the app deleted the portion of the password I previously typed and required me to start from scratch.  We need to revise this behaviour - the password should not be deleted.

**Comment by Jiandong-Guo** [comment]
seems fixed, need more test

**Comment by mullhol** [comment]
Confirmed implemented
