### ISSUE TITLE
SM Testing - receiving multiple notifications when opening the app 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#197]
Joelle is currently not receiving notifications on a random schedule. When she opens the app, she receives numerous notifications immediately.  After closing the app, she does not receive notifications again until she re-opens the app.  

Device: Redmi Note 7, Android OS 10 QKQ1 190910.002

**Comment by AJBouzidi** [comment]
@mullhol 
One of the cause will be the power saving set on android phone. and we believe that Well-being check app could be part of applications that been chosen by the OS to save the power. Therefore, the Notifications channel is disabled for the mobile application when the phone is on saving mode.

Please follow the steps on the document to see if this is will work. 

[REMOVE BACKGROUND RESTRICTION(GitUAT#197).docx](https://github.com/StatCan/WellbeingCheckUAT/files/5132972/REMOVE.BACKGROUND.RESTRICTION.GitUAT.197.docx)
Email has been sent to Joelle with the attached document.

**Comment by AJBouzidi** [comment]
one other solution could be the permission when the screen locked : 
Could you please try this for Redmi Note 7:
Go to Settings -> Permissions -> Other permissions, and select app (Well-being Check) to enable 'Show on Lock Screen'

**Comment by mullhol** [comment]
Joelle confirms the setting changes resolved the issue.  I will work with COMM to develop FAQ content for this based on the required settings changes.
