### ISSUE TITLE
Name of app at bottom of screen

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#199]
The name of the app has been separated from the graphic on the splash screen. It's all the way at the bottom of the page. Can we correct this please? 

![image](https://user-images.githubusercontent.com/59370537/91340786-90e90880-e7a6-11ea-98f4-e5099a2643bb.png)

**Comment by mullhol** [comment]
I opened the app numerous times - it was at the bottom each time.

**Comment by Jiandong-Guo** [comment]
Fixed

**Comment by mullhol** [comment]
Confirmed implemented
