### ISSUE TITLE
SM testing - Error when calling questionnaire 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#205]
Patricia updated her app and called a questionnaire.  She received the following error message on the EQ screen: 

![image](https://user-images.githubusercontent.com/59370537/93105200-c5046a80-f67c-11ea-9518-acc4b0cf362f.png)

She immediately closed the app, signed back in, called a questionnaire, and it worked.  Do we know what this error is/why it happens?  Is there anything to be done here?

**Comment by AJBouzidi** [comment]
This is need to be tested on the E2E Testing in production

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo @AJBouzidi 
Issue cannot be reproduced and reporter is no longer experiencing this issue
