### ISSUE TITLE
Leave test group 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#206]
Rachel is not receiving notifications.  Her note: "when I went to download the last version of the app, I accidentally pressed ‘leave testing program’. I was able to rejoin with the same button and since the app downloaded fine, I assumed it wasn’t a problem. But could this be the reason why no notifications are scheduled?"

**Comment by Jiandong-Guo** [comment]
Leaving and re-joining the testing team is not a problem as long as she can install the app. Right ,Ali ?
Please check:
   In contact screen, click INFO button, see if a scheduled list is there, if no, check the notification switch in setting screen to make sure it's ON,  and make sure the surveyA is done.  if there is a list after clicking  INFO button, that means the schedule was setup, please check device setting to make sure notification is enabled.

**Comment by mullhol** [comment]
She checked all of these things, and they were all correct already.  She completed a questionnaire B and it scheduled notifications for her after.  I expect she may have been outside of the 4 day window of Questionnaire B submissions. 

cc @Jiandong-Guo @AJBouzidi
