### ISSUE TITLE
Accessibility testing : Mailing address

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#208]
Please revise "Mail" in the contact us menu to: 

Mailing address / L'adresse postale

**Comment by mullhol** [comment]
There is a typo in the English, and the french has not been updated. @AJBouzidi please revisit this ticket. 

![image](https://user-images.githubusercontent.com/59370537/95686740-e39f4800-0bcd-11eb-8920-d46f58992126.jpeg)
![image](https://user-images.githubusercontent.com/59370537/95686741-e732cf00-0bcd-11eb-8f1b-09463a9bc192.jpeg)

**Comment by AJBouzidi** [comment]
This is done and will be in the next release.

**Comment by mullhol** [comment]
Confirmed corrected
