### ISSUE TITLE
Last chance notification

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#210]
I completed a questionnaire submission yesterday, but received the last chance notification today (we haven't heard from you in a while...). This should only be sent to the respondent after 4 days of non-submission.

**Comment by mullhol** [comment]
I still received a scheduled notification after the last chance notification. The last chance notification was sent in addition to the scheduled notifications, totalling 6 notifications today. 

![image](https://user-images.githubusercontent.com/59370537/94630462-d744f200-0293-11eb-9794-a089ebe7dc2e.png)
![image](https://user-images.githubusercontent.com/59370537/94630468-dd3ad300-0293-11eb-94b2-c7a3cc412772.png)

@Jiandong-Guo @AJBouzidi

**Comment by Jiandong-Guo** [comment]
app version will be added to the notification title


![n](https://user-images.githubusercontent.com/58485300/95117770-1b624780-0717-11eb-98c1-7e2445dc3ae1.png)

**Comment by mullhol** [comment]
Issue has not replicated in current app version
