### ISSUE TITLE
URL to be used in hyperlinks

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#211]
The URL to be used in the FAQ is: 

www.statcan.gc.ca/wellbeing

www.statcan.gc.ca/bienetre

English link to be used in:
Is this a legitimate Statistics Canada study / Why are you conducting this study?

French link to be used in: 
Est-ce une enquête légitime de Statistique Canada? / Pourquoi menez-vous cette enquête?

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the October 9th release.

**Comment by mullhol** [comment]
Confirmed implemented
