### ISSUE TITLE
Accessibility Testing : Format of headings

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#212]
The section on "Why we conduct this survey" must use headings to introduce each section using a heading level hierarchy:
H2 Why we conduct this survey
H3 Notifications
H3 Confidentiality
H3 Record linking
H3 Time to complete this questionnaire
H3 Timeout 
H3 Definitions 

In addition, the "Contact Us" section must use headings to introduce each subsection. for example:
H2 Email
H2Telephone
H2 Website

Solution:  Use html heading markup

**Comment by AJBouzidi** [comment]
@mullhol we have to add to this issue the T&C page too ?

**Comment by mullhol** [comment]
@AJBouzidi To be safe, I would.  It wasn't identified in the accessibility report, but it would make everything more accessible.
