### ISSUE TITLE
Accessibility Testing : Info button 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#214]
Info" button seems to be broken.
Description: The "Info" button leads the respondent to a page where only the "Contact Us button appears. 

Recommendation: Either offer more information for the page stemming from the "Info" button or remove it. 

Solution - Find out how to include more information on page or move button.

**Comment by AJBouzidi** [comment]
Info button: This button was needed to test the notifications list (on the Contact screen).  This button will be removed when the testing end.

**Comment by mullhol** [comment]
@AJBouzidi Ahhh, I interpreted this issue as the Information button on the homepage.  Should we close this ticket then, or wait until the info button is removed?

**Comment by AJBouzidi** [comment]
@mullhol wait until the info button removed.

**Comment by Jiandong-Guo** [comment]
Removed

**Comment by Jiandong-Guo** [comment]
Re-open it for testing

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Please remove the button. Thank you.

**Comment by Jiandong-Guo** [comment]
It's done, please check in next release

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Done - please close the ticket
