### ISSUE TITLE
Accessibility Testing: Thank You Toast 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#215]
No notice after submitting the EQ.
Thank you for checking in. Pop up saying thank you does not work.

Description: After completing the EQ, and tapping the "Submit" button, there is no notice to users that there EQ has been successfully submitted.

Recommendation:
After respondents have submitted their survey, they should be offered a page displaying something similar to "Thank you for completing this survey..."
 
Solution:  Plan A: use Aria = Alert. Other options will be investigated.

**Comment by AJBouzidi** [comment]
![Simulator Screen Shot - iPhone X - 2020-10-29 at 22 29 00](https://user-images.githubusercontent.com/58231743/97653615-94fc0580-1a37-11eb-80de-fa1cf9b3adbb.png)
![Simulator Screen Shot - iPhone X - 2020-10-29 at 22 29 52](https://user-images.githubusercontent.com/58231743/97653613-94636f00-1a37-11eb-98b9-6ec590ada2c6.png)

**Comment by SBleeks** [comment]
In order to confirm whether or not this text and design functionality are accessible, this page will need to be tested using the native app. In other words, a screen cap can't confirm the functionality nor the text that will be identified by various access technologies.
Can someone confirm if this "thank you..." message "toast" page is offered as part of the latest Welbeing check app update?

Either way, the new design of the "toast" page will need to be tetested via the mobile app.

**Comment by mullhol** [comment]
@SBleeks This has not been released for testing yet. We will update you when it is available.

**Comment by Jiandong-Guo** [comment]
Just change toast message to popup message, ready to test in next release.

**Comment by Jiandong-Guo** [comment]
What I found from the old document is:
![image](https://user-images.githubusercontent.com/58485300/100473412-4da37c00-30ac-11eb-8d41-02ab67d1243a.png)

Since it seems not a big issue, will change it after confirm with SMA

**Comment by mullhol** [comment]
New thank you message appears, but old toast still appears in background.  The toast needs to be removed, we should only have one thank you message.  

![image](https://user-images.githubusercontent.com/59370537/101827782-b3f1bb00-3afe-11eb-937a-b942cd3363c9.png)

**Comment by Jiandong-Guo** [comment]
The toast text was removed, will see in next release

**Comment by mullhol** [comment]
@T-T-Nguyen This is ready for Stacy to test

**Comment by Jiandong-Guo** [comment]
Close ticket on behalf of Trish
