### ISSUE TITLE
Accessibility Testing : 24 hour clock 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#218]
Settings page
Description: The "Do not disturb before 8:00 and do not disturb after 22:00" statement should be improved to provide context. 

Recommendation: Change the statement to include the letter "h" to provide the necessary context referring to the hour time of day. 
Or change the time reference to “8:00 AM" and"10:00 PM". 
Note: The 24 hour clock should be used for the French version. In other words, we cannot use "10:00 PM" for the French version. Use 22:00 h as defined in the Canada.ca Web content style guide.

Each fix, use right context… Stacy will provide context.

**Comment by AJBouzidi** [comment]
@mullhol Timepicker has been changed to match the language in the settings screen. 
we need to change the backend and AM PM on the settings. this is will be done for next week.

**Comment by AJBouzidi** [comment]
@mullhol done for the iOS. Could you please test the for the iOS version. 
we still working on the android version.

**Comment by mullhol** [comment]
Working on iPhone

**Comment by Jiandong-Guo** [comment]
So we have to change 2 parts.   one is in setting page,  another is the time picker. 
The time picker for ios is right now, we have to change setting page for ios.
for android, we have to change both the setting page and time picker.

 Is it right ?

**Comment by mullhol** [comment]
@Jiandong-Guo The ios is already correct based on previous work completed for this ticket.  AM and PM show on the settings page.  I believe it is only android work remaining.  @AJBouzidi can you confirm?

**Comment by AJBouzidi** [comment]
@AJBouzidi setting page for iOS is done. the AM and PM are done.

**Comment by Jiandong-Guo** [comment]
@AJBouzidi I checked setting page, when you set time 12:00h in french, will show 0:00 PM in english,  Seems no such use 0:00 PM,  Please make sure

**Comment by mullhol** [comment]
Ticket on hold until Android version can be deployed for testing

**Comment by Jiandong-Guo** [comment]
Close ticket on behalf of Trish
