### ISSUE TITLE
Accessibility Testing: Session Timeout 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#219]
The session timeout will stay at 7 minutes, however please revise the session timeout text on both the Getting started page and info page to the following: 

Session timeout 
After 7 minutes of inactivity, your session will time out and Well-Being Check will lock. You will need to enter your password to continue. You will not be able to access any unsaved information. 

Délai d’inactivité d’une session 
Après 7 minutes d’inactivité, votre session sera interrompue et l'application Bilan bien-être se verrouillera. Vous devrez entrer votre mot de passe pour continuer. Vous ne pourrez accéder à aucun renseignement qui n’a pas été sauvegardé.

**Comment by AJBouzidi** [comment]
@mullhol the message 'After 2 hours of inactivity, your session will time out. You will not be able to access any unsaved information. " need to be removed?

**Comment by mullhol** [comment]
@AJBouzidi The content that is previously under session timeout should be replaced with the content I put in the ticket above. Ultimately the 7 minute app timeout overrides the EQ session timeout, so we're modifying the message to one timeout instead of two, and reformatting so both the information about entering the password and accessing unsaved information are still covered.  Make sense?

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the October 9th release.

**Comment by mullhol** [comment]
Confirmed implemented
