### ISSUE TITLE
Revision to FAQ 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#220]
Please revise the FAQ response for "How long will it take me to complete the study? / Combien de temps me faudra-t-il pour terminer l’enquête?" to the following: 

Daily Well-being Checks should take about 2 minutes to complete. You can choose how many times to participate each day by customizing the number of notifications you will receive in the settings menu. We are asking you to participate in the study for one month.

Le Bilan bien-être devrait prendre environ 2 minutes à remplir. Vous pouvez choisir le nombre de fois que vous souhaitez participer chaque jour en personnalisant le nombre de notifications que vous recevrez dans le menu des paramètres. Nous vous demandons de participer à l’étude pendant un mois.

**Comment by AJBouzidi** [comment]
This is has been fixed and will be in the October 9th release.

**Comment by mullhol** [comment]
Confirmed implemented
