### ISSUE TITLE
Terms and Conditions - English 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#222]
There is a line in the Privacy notice which should not be there (it accompanied the link we previously removed). Please removed "Privacy and confidentiality of personal information" from the end of the privacy notice paragraph (bolded content in content below). No change required in French version. 

Privacy notice
Statistics Canada is committed to respecting the privacy of individuals and businesses—whether they are responding to one of our surveys, providing personal information, purchasing a product or service or using our website. To fulfill this commitment, Statistics Canada has created a Privacy Framework that describes the Approved practices, procedures and governance related to privacy. All personal information collected, used, disclosed or retained by Statistics Canada is protected by the Privacy Act and by the Statistics Act whether it was provided by a respondent or received from a third party.  **Privacy and confidentiality of personal information**

**Comment by AJBouzidi** [comment]
Done. this is will be part of the next released.

**Comment by mullhol** [comment]
Confirmed corrected.
