### ISSUE TITLE
SM Testing: Notifications received at same time

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#224]
Joelle received two notifications at the same time. 

![image](https://user-images.githubusercontent.com/59370537/96886990-1eb53d00-1452-11eb-8d90-e03bdd7d9c3c.png)

**Comment by AJBouzidi** [comment]
@mullhol I notice even the notifications has been received at the same time it's been triggered in the different time.
first one at 13:00 and the second at 14:14.
the OS holding the notifications until the user activate the phone again.

**Comment by mullhol** [comment]
@AJBouzidi I noticed the same thing so I asked her to check her battery saver settings again, but they were ok this time.

**Comment by AJBouzidi** [comment]
@mullhol let's see if this is will resolve the issue of delayed notifications on the Redmi Note 7. 
this is the step by step how to turn off MIUI Optimization. 
[TurnOffMIUI.docx](https://github.com/StatCan/WellbeingCheckUAT/files/5453706/TurnOffMIUI.docx)

**Comment by zhuelle** [comment]
@AJBouzidi Please provide comment that we cannot fix;

**Comment by Jiandong-Guo** [comment]
Local notification delayed problem involves many device settings such as battery usage, background process, power saving mode.  please reference 
 https://www.hongkiat.com/blog/solve-android-delayed-notifications/

**Comment by Jiandong-Guo** [comment]
Close according to Trish's email

**Comment by T-T-Nguyen** [comment]
Joelle -Android V10   MIUI V12.5.1 | EN | Redmi Note 7

- Downloaded the app
- Accepted Terms and Conditions
- Changed to French and notifications per day to 5 in Settings
