### ISSUE TITLE
Android asks to re-create password after updated.

### ISSUE THREAD

**Issue by Jiandong-Guo** [StatCan/WellbeingCheckUAT#226]
Problem: After the app updated, The app asks to re-create password after updated, actually it re-creates the new account, and need to re-do survey a.
Reason: The local storage will be erased after the app updated. it is an react native issue.

**Comment by mullhol** [comment]
@Jiandong-Guo Boht Trish and Rachel have mentioned they have successfully updated the app in the past without needing to re-create their account.  This seems to be an issue we have introduced somewhere along the line - perhaps in attempt to delete the last version's notifications?

**Comment by Jiandong-Guo** [comment]
@mullhol @AJBouzidi 
   Ali have successfully updated the app in this version without needing to re-create their account.  
  Also the local storage is in the launch screen, what we modified in this version is checkUpdate function that is different one.
  will continue to check it to see if can find some problem. but the most possible problem is the local storage package which is deprecated.

**Comment by Jiandong-Guo** [comment]
@AJBouzidi 
When you build the android bundle, Which laptop do you use ? MacBook or laptop ?

**Comment by AJBouzidi** [comment]
@Jiandong-Guo I use the Mackbook.

**Comment by zhuelle** [comment]
@Jiandong-Guo, Please add comments in this ticket to clearly describe the issue and why the dev team cannot fix the issue so business can use it to make a decision.

**Comment by Jiandong-Guo** [comment]
The reason is the local storage will be erased after the app updated for some phones. it is an react native issue.  The React native community(internet) suggests to try to upgrade SDK and change local storage package and it MAY fix the problem.

**Comment by Jiandong-Guo** [comment]
Close according to Trish's email
