### ISSUE TITLE
Notifications received too close to each other 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#227]
Joelle received two notifications within less than an hour of each other.  This should not be possible. 

![image](https://user-images.githubusercontent.com/59370537/98884975-29fef580-245f-11eb-8b86-7e2add04d367.png)

**Comment by Jiandong-Guo** [comment]
Please test in next release

**Comment by mullhol** [comment]
@Jiandong-Guo This is essentially the same issue Rachel is experiencing in ticket 232.  That issue is outstanding. Joelle is currently testing for her phone/this ticket, now that she can receive notifications.  However ticket 232 is evidence this is a more widespread issue than just one device. 

CC: @T-T-Nguyen

**Comment by Jiandong-Guo** [comment]
@mullhol, It seems still my previous test version, because it shows 1.4.9, (the 1.4.9 I used for testing upgrade, which is manually deployed), Please uninstall/delete and re-install it, and scroll down in information screen, check the version number and let me know if the version number is 1.4.8

**Comment by mullhol** [comment]
@Jiandong-Guo The 1.4.9 screenshots were from mid-November. I'll ask Joelle to confirm what her app is now however. In ticket 232, Rachel is experiencing this issue with version 1.4.8

**Comment by Jiandong-Guo** [comment]
@mullhol Yes, I found the problem now, please see #232, because that is old logic problem, we didn't touch it in both 1.4.8 and 1.4.9, so it happens in both versions,

**Comment by mullhol** [comment]
@Jiandong-Guo Ok great, glad you found it.  Joelle confirmed she is using 1.4.8 now as well, so everyone should be on the correct version at least. We'll retest these issues in the next update.

**Comment by Jiandong-Guo** [comment]
Close according to Trish's email
