### ISSUE TITLE
Notification received approx. 7 hours late 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#228]
Joelle received a notification approximately 7 hours late. We can see it was scheduled for 7:57, but was only received at 16:24. 
![joelle1](https://user-images.githubusercontent.com/59370537/98885240-aeea0f00-245f-11eb-94cf-c2659812386e.jpg)

**Comment by Jiandong-Guo** [comment]
It is the same issue as #224

**Comment by mullhol** [comment]
Closing due to link to 224.
