### ISSUE TITLE
Last chance notification received too early 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#230]
Rachel received the last chance notification after only 2 days of not completing surveys.

**Comment by Jiandong-Guo** [comment]
Please test in next release

**Comment by mullhol** [comment]
I will have Rachel test this when we are able to release to Android again.

**Comment by mullhol** [comment]
@Jiandong-Guo Rachel received the last chance notification one day early with the current app version.  She completed a questionnaire repsonse on Thursday.  She received her daily notifications Friday, Saturday, and Sunday.  She received the last chance notification Monday. 

We still have an issue here. She should have received daily notifications on Monday, and last chance on Tuesday. 

CC: @T-T-Nguyen

**Comment by Jiandong-Guo** [comment]
@mullhol, The last chance will be sent on day 5.
    She completed EQ on Thursday,  on this day she may not receive notification depends on the current time, but this day will be counted (no matter notification is arranged or not).
So Thursday is day1, Friday is day 2, Saturday is day 3, Sunday is day 4, Monday is day 5,  last chance day is Monday.

**Comment by Jiandong-Guo** [comment]
Close ticket on behalf of Trish
