### ISSUE TITLE
Additions to FAQ

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#231]
Content Specification.xlsx
https://gcdocs.gc.ca/statcan/llisapi.dll/link/8007177

1) Please add FAQ responses from lines 66 and 68 of the FAQ tab on the content spec to both English and French versions of the app.  They should appear in the app in the same order they are noted in the spec content.  

2) Please correct line 70 in the English version of the app to "If none of these scenarios...." (Current content includes "neither"). No change required to French version. 

3) Please add new FAQ Section to both English and French version of app, Respondent Well-being. This section and it's FAQ question/response are in lines 98-100 of the spec. Hyperlinks required are in lines 102 and 103.

**Comment by Jiandong-Guo** [comment]
Ready to test in next release

**Comment by mullhol** [comment]
Implemented.
