### ISSUE TITLE
SM Testing - Received an early notification 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#232]
From Rachel: At 8:35 I received a notification and completed the questionnaire. Then I checked the schedule, and saw that I had received this notification about five minutes early and the scheduled time was still listed. At 8:41 (the prescheduled time) I received another notification and completed the questionnaire again. I am only signed up for two per day, and have another one scheduled for around noon. When I took a screenshot of the schedule on Tuesday, my first notification was scheduled for 8:42, one minute later than it was today, I’m not sure if that change would make a difference.

Rachel did not note the time stamps in the notifications, but did confirm she received two notifications yesterday, so this is not a late notification from yesterday's schedule.

**Comment by Jiandong-Guo** [comment]
Please test it again

**Comment by mullhol** [comment]
From Rachel: 
Tuesday December 8:  I deleted and reinstalled the app, immediately completing a questionnaire.  

Wednesday December 9: I received two notifications but did not respond to them.

Thursday December 10: I received my first notification at 8:25 (screenshot 1). This was one minute after the time that the notification had listed, which was aligned with the schedule from Tuesday (screenshot 5). I immediately completed the questionnaire, and right after completing it, I got another notification at 8:27 (screenshot 2). This one was listed as scheduled for 8:18, which lined up with the Thursday schedule (screenshot 3).  I also received a third notification in the afternoon (screenshot 4). I did not see it right away, so I don't know exactly if it came on time, early or late. This notification lined up with the schedule from Thursday. I completed this questionnaire and did not receive an additional notification.

![image](https://user-images.githubusercontent.com/59370537/102252382-04d52b00-3ed4-11eb-9eca-a41220462bb5.png)

![image](https://user-images.githubusercontent.com/59370537/102252416-11598380-3ed4-11eb-9226-e4a101080eac.png)

![image](https://user-images.githubusercontent.com/59370537/102252468-1ddddc00-3ed4-11eb-8faa-be5c41275ced.png)

![image](https://user-images.githubusercontent.com/59370537/102252508-29310780-3ed4-11eb-9904-ff5eb2975297.png)

![image](https://user-images.githubusercontent.com/59370537/102252660-55e51f00-3ed4-11eb-9ead-8e40f49f5a73.png)

CC: @T-T-Nguyen

**Comment by Jiandong-Guo** [comment]
@mullhol, I finally find the problem, The flow is:
1) On Dec08, schedule was setup (Dec 10 8:24 is one in that list),
2)On Dec10, Rachel finished a survey B, the old list removed and a new list was created(Dec10 8:18 is in it),
3)During creating the new list,  because no setting changed, so should just append list for Dec12,Dec13,
4)But the problem is the list for Dec10 and Dec11 were also created. 
I will check the logic and fix it

**Comment by Jiandong-Guo** [comment]
Close ticket on behalf of Trish
