### ISSUE TITLE
SM Testing - unprompted EQ response

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#233]
Rachel received the last chance notification on a Monday. She completed a questionnaire submission after receiving it. 

On Tuesday, she completed a questionniare without having been prompted by a notification. She checked her schedule after, and only one notification was scheduled for that day.  There should have been two. 

Was there an error in the notification schedule? Or was a notification somehow deleted based on her unpromted response?  A respondent should be able to respond as many times as they wish in a day - those responses should not affect their scheduled notifications.

**Comment by Jiandong-Guo** [comment]
This one should not be a problem.
On Tuesday, After a survey B done, the schedule function detected the 4 days range had passed, and last day is not reached.
so the scheduler will setup a notification list for at most another 4 days. suppose 2 notifications per day. but how many notifications will be ranged for the first day is based on current time, it maybe 2 notifications, maybe 1 notification, maybe even no notification at all.

**Comment by mullhol** [comment]
@Jiandong-Guo The methodology for the notification strategy was supposed to be as follows: 

Respondent downloads the app. 
Respondent does not change their notifications, so they should receive 2 notifications daily. 
Respondent completes questionnaire A. 
Respondent will receive 2 notifications that day, ultimately completing 3 questionnaire submissions. 

Each day after, they should receive 2 notifications unless they change their notification preferences. 

We did discuss the option at one point of counting their completion of questionnaire A as a "notification response", and methodology and SM chose the option as outlined above as we were told it was the easier programming option.  **Since the second option has been programmed however, we can leave that component of the notification strategy AS IS, so Questionnaire A will continue counting as a "notification response".** Methodology and SM accept this.

The outstanding issue is the elimination of notifications if a respondent decides to complete a questionnaire B without having received a notfication. For example, on Tuesday the respondent is scheduled to receive 2 notifications.  That morning, they are taking part in an interesting activity and decide to complete a questionnaire submission without having received a notification. They should still receive their 2 scheduled notifications that day, for a total of 3 questionnaire submissions. 

**An un-prompted questionnaire B response should never remove notifications from the schedule**, as that breaks the randomized requirement of the study's methodology.

**Comment by Jiandong-Guo** [comment]
I think we don't need change it following the notification discussion

**Comment by mullhol** [comment]
@Jiandong-Guo 
Per Amanda: All of the specs Jiandong provided talk about scheduled notifications, not unprompted situations where the respondent just decides to go in and do the survey on a whim. So maybe I am misunderstanding something but I still agree with you that unprompted responses should not impact the notification scheduler (only changes to the settings such as awake time , sleep time or number of notifications should have an impact on the scheduler).

**Comment by zhuelle** [comment]
@mullhol Based on your comments, there should be no changes to the existing code. Can we close this ticket?

**Comment by mullhol** [comment]
@zhuelle I need to do some testing of this on my own before I can confirm that. Rachel has experienced notificationsbeing removed from her schedule if she completes an unpromted response. I haven't noticed that in the past but I will test over the next day to see if this happens for me as well.  If so, we need to continue to investigate.  If not, I'll look at closing the ticket.

**Comment by mullhol** [comment]
Adding Jiandong's emailed response here for documentation purposes...

Actually we don’t have the concept of unprompted EQ, during a day, 
1)	User can do any times of survey during a day
    2)   After each of the survey, the scheduler will check if we need to append new schedule to that list
3)   If needed(Normally after  the first time of that day) ,   a new schedule list will be appended
4)   If No, do nothing about the schedule
5)  The app has no idea which EQ is associated to which schedule

**Comment by Jiandong-Guo** [comment]
@mullhol,  as the strategy discussed,  for example the notification number is 2, after the user received last chance and after user done a survey B, be aware of that the number of notification for the first day is 1(2-1, the 1 is the time the user just did ),

**Comment by mullhol** [comment]
@Jiandong-Guo Yes, but the issue happened on day 2.  She received the last chance notification on Monday and completed a submission.  On Tuesday, she completed an unprompted submission, and when checking her schedule after that there was only one notification listed. 

In my testing today, I'm not triggering this issue. It's possible something else happened.  I woud like to test tomorrow as well before closing the ticket. If my testing tomorrow is correct as well, I will close the ticket and ask Rachel to continue monitoring on her device.  

@T-T-Nguyen, can you please test this issue on your android as well so we have both iPhone and Android verified?

**Comment by Jiandong-Guo** [comment]
Maybe after this weekend, I will do a new release this weekend

**Comment by Jiandong-Guo** [comment]
Also during test, please write down or screenshot that list, after a survey B done, only the newly appended list will show there, you will not see the old list anymore(Yes, they are already sent to OS)

**Comment by Jiandong-Guo** [comment]
Close ticket on behalf of Trish
