### ISSUE TITLE
Missing Period in FAQ

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#235]
The phone number at the end of the English response to FAQ ‘Why am I no longer receiving notifications’ should be followed by a period.

**Comment by mullhol** [comment]
This issue impacts the french version as well.  

![image](https://user-images.githubusercontent.com/59370537/102250329-719af600-3ed1-11eb-9de7-94e7f0eb0b2e.png)

cc: @T-T-Nguyen

**Comment by Jiandong-Guo** [comment]
Fixed and please test in next release

**Comment by mullhol** [comment]
confirmed implemented
