### ISSUE TITLE
SM Testing: Notifications missing for days 

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#237]
Joelle deleted her app and downloaded the newest version on Tuesday, December 8. She immediately confirmed her battery saver settings would allow notifications from the app. Regardless of this, she did not receive notifications from Tuesday-Monday December 14. On the 14th, she clicked on her schedule button to confirm she had a schedule.  After that, notifications started. 

This is concerning... being a fresh download of the app, it should not have required her to troubleshoot the receipt of notifications. Is there logic why clicking on the schedule would have started the receipt of them? 

CC: @T-T-Nguyen

**Comment by Jiandong-Guo** [comment]
@mullhol There is no relation between the Info button and the notification,  Click the info button is just check if the schedule list was sent to OS, if the list was sent already, that means nothing about the app side, we have to check the device setting side.

**Comment by mullhol** [comment]
@Jiandong-Guo Are there settings in particular she should check?

**Comment by Jiandong-Guo** [comment]
Close according to Trish's email
