### ISSUE TITLE
New FAQ

### ISSUE THREAD

**Issue by mullhol** [StatCan/WellbeingCheckUAT#238]
Please add the following FAQ to the Settings and Notifications section of the FAQ.  It should be placed after the FAQ "Why am I no longer receiving notifications?" 

**Why am I receiving duplicate notifications?**
If Statistics Canada is forced to perform an update to the Well-being Check App   during your participation in this study, there is a chance that you will   receive duplicate notifications for up to four days. If you experience this,   there is no need to respond to the questionnaire two times in a row.

**Pourquoi est-ce que je reçois des avis en double?**
Si Statistique Canada doit mettre à jour l’application Bilan bien-être pendant que vous participez à cette étude, il est possible que vous receviez des avis en double pendant un maximum de quatre jours. Si cette situation se produit, il n’est pas nécessaire de remplir le questionnaire deux fois d’affilée.

**Comment by mullhol** [comment]
CC @t-t-nguyen

**Comment by Jiandong-Guo** [comment]
Ready for test

**Comment by Jiandong-Guo** [comment]
Close according to Trish's email
