### ISSUE TITLE
Add FAQ Content - Covid-19 restrictions

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#239]
Please add the following:

Why are some things that are prohibited due to COVID-19 restrictions included as potential responses to questions in this survey?	
Some of the response categories to the questions ‘Where are you?’, ‘What are you doing?’, or ‘Who are you with?’ may go against COVID-19 restrictions in your region. They have still been included because provincial and municipal responses to the pandemic vary and may be adjusted throughout the survey collection period. Additionally, many activities that used to be only available in-person are now being conducted virtually. For example, you might be visiting a museum through an online exhibit while still being at your own home.	

Pourquoi certaines choses interdites en raison des restrictions liées à la COVID-19 sont-elles incluses comme réponses possibles aux questions de cette enquête?
Certaines catégories de réponse aux questions « Où êtes-vous? », « Que faites-vous? » ou « Avec qui êtes-vous? » peuvent aller à l’encontre des restrictions liées à la COVID-19 dans votre région. Elles ont quand même été incluses parce que les mesures prises par les provinces et les municipalités en réponse à la pandémie varient et peuvent être ajustées tout au long de la période de collecte de l’enquête. De plus, de nombreuses activités autrefois offertes en personne seulement ont maintenant lieu virtuellement. Par exemple, vous pourriez visiter un musée au moyen d’une exposition en ligne sans quitter votre domicile.

NOTE: This will go after the question and content of: Why are you conducting this study?
Line 14 and 15 of as ordered: https://gcdocs.gc.ca/statcan/llisapi.dll?func=ll&objaction=overview&objid=13040294

**Comment by Jiandong-Guo** [comment]
Added, Ready to test in next release

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Done
