### ISSUE TITLE
FAQ Addtion: Data Storage and Protection

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#240]
Please add the following text:

Well-being Check uses Statistics Canada’s Electronic Collection Portal to collect your responses. For more information about the security features in place to protect your data, please visit {insert link}.

Le Bilan bien-être utilise le portail de collecte électronique de Statistique Canada pour recueillir vos réponses. Pour plus d’informations sur les dispositifs de sécurité mis en place pour protéger vos données, veuillez consulter [insérer le lien].

https://surveys-enquetes.statcan.gc.ca/en/faq/security-securite.html
https://surveys-enquetes.statcan.gc.ca/fr/faq/security-securite.html

Note - This should be added after the text below as per Line 43 in  https://gcdocs.gc.ca/statcan/llisapi.dll?func=ll&objaction=overview&objid=13040294 

How is my data stored and transmitted? How will my data be protected?	
The Well-being Check app fully complies with all privacy and security regulations in place to protect Canadians’ information.	

AND

Comment mes données sont-elles stockées et transmises? Comment mes données seront-elles protégées?
L’application Bilan bien-être est entièrement conforme à toutes les réglementations en matière de protection de la vie privée et de sécurité mises en place pour protéger les informations des Canadiens.

**Comment by Jiandong-Guo** [comment]
It was added and ready to test in next release

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo 
![image](https://user-images.githubusercontent.com/59370759/108083427-0c828e80-7041-11eb-9d90-218dc43f2a72.png)
