### ISSUE TITLE
Issue: French/English Questionnaire Toggling

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#242]
Issue reported by Sylvie L.

LAST NIGHT:
User’s device is in English.
French flag is on the sample file
When opened the app, it was in English.
Entered the setting/language to set it back to French
Completed the questionnaire
Brought user back to the shell and it was English.
Forced stop and started the app again
The app was in French and started the questionnaire in French
Switched the language again and had the same problem (but in reverse)

THIS MORNING :
App is in French
Questions are always in English

_Also…  Are we supposed to be able to toggle back and forth from English to French and back when in the questionnaire?  That’s something I do regularly, especially when we are using specific terms…  Seeing the translation helps in figuring out what is meant sometimes…._

**Comment by T-T-Nguyen** [comment]
Response to Italic text:
That's a functionality of EQ, but it was removed from the app very early on. It wasn't possible to have the EQ and app talk to each other to manage the toggle from the EQ side, only from the app side. 

Thank you @mullhol

**Comment by Jiandong-Guo** [comment]
Fixed by re-deploy webapi
