### ISSUE TITLE
Google Play Update: Address and Branding

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#244]
Hi Jiandong, 

Please see the attached screenshots 

App Branding: Are we able to modify the French label as Statistiques Canada? 

Address:  Should also be in French - The issue is seen in the other image.

![Screenshot_20210215-165813_Google Play Store](https://user-images.githubusercontent.com/59370759/107996943-a39f0600-6faf-11eb-8383-5ca6c760fd21.jpg)

![Screenshot_20210215-165827_Google Play Store](https://user-images.githubusercontent.com/59370759/107996959-ac8fd780-6faf-11eb-953c-8017e5d84046.jpg)

**Comment by Jiandong-Guo** [comment]
This message is from developer info, no way to input 2 different strings.
Can we just input both language in one string like 
Statistics Canada | Statistiques Canada


![image](https://user-images.githubusercontent.com/58485300/108084684-8404ed80-7042-11eb-9ad1-ae9e4a231951.png)

**Comment by T-T-Nguyen** [comment]
Statistics Canada
150 Tunney's Pasture Driveway
Ottawa, Ontario
K1A 0T6

_______________________

Statistique Canada
150, promenade Tunney's Pasture
Ottawa, Ontario
K1A 0T6

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo I do not have permission to re-assign this to you

**Comment by T-T-Nguyen** [comment]
What's New
Beta Test

Quoi de neuf?
Test Bêta

**Comment by T-T-Nguyen** [comment]
Address text removed
