### ISSUE TITLE
Notification Title/App name not in French

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#245]
App name is showing up as Well-being Check, it should be Bilan bien-être 

![App name not in French](https://user-images.githubusercontent.com/59370759/108214432-2afa8f80-70fe-11eb-9f23-1fc726edf6e8.jpg)

@Jiandong-Guo I do not have permission to assign

**Comment by Jiandong-Guo** [comment]
This is the app name, same thing like the app name displayed on phone desktop. That is not from store listing.
If persist on this, we can try in next release, we have to give a specific name.

**Comment by T-T-Nguyen** [comment]
Well-being Check | Bilan bien-être

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo The title remains the same

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo the notification label still shows up in English only on my Android

@mullhol confirmed that her notification label shows up as Well-being Check | Bilan bien-être

**Comment by zhuelle** [comment]
@Jiandong-Guo  could we do more reasearch on resolving this ticket? Apparently, it works for ios but not android.

**Comment by zhuelle** [comment]
@Jiandong-Guo this is still not working after the new release on April 24th. The notification for Android displays only English.

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo This can be closed as the solution is to have a bilingual app name.
