### ISSUE TITLE
Results Screen - Blank

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#246]
@Jiandong-Guo Several testers have indicated that they do not see Results (dashboards) after completing the questionnaire 3+ times.

Example from Amanda:
![Blank_Result](https://user-images.githubusercontent.com/59370759/108722498-3a5c4d00-74f1-11eb-964e-d7af2b286869.png)

**Comment by T-T-Nguyen** [comment]
![SpouseandPets_ NoResults](https://user-images.githubusercontent.com/59370759/116081797-b0537080-a668-11eb-9e41-4a3244b4bffb.jpg)

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo testers are still indicating they are not getting results - specifically after selection spouse and/or pets.

**Comment by Jiandong-Guo** [comment]
What will happen after doing another surveyB ?

**Comment by Jiandong-Guo** [comment]
Is the graph in another language blank too ?
When this happens, please click the info button to record the device Id and ask CMP to open database table to check the data for this device id.

**Comment by Jiandong-Guo** [comment]
When this happens, please follow the steps below to troubleshot it:
1) switch to another language(in app setting, not device setting),  to see the same graph is blank too.
2)click Info button to record the device Id, and indication number.
3)go back to home screen, waiting for 5 minutes, and click result button again, to check the same graph is blank too

**Comment by zhuelle** [comment]
I have a feeling that the issue is with datapoints miss match between survey and CMP dashboard, e.g. the Pet is not showing etc. @T-T-Nguyen is the SMA investigating this by checking the specs?

**Comment by T-T-Nguyen** [comment]
@zhuelle Yes they were able to retrieve the data 
I provided them the specifications that Holly provided from past emails

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo @zhuelle Specs have been updated by SMA and a change management ticket is being reviewed.

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo @zhuelle We are waiting for @thierryrama to review and update the dashboard specs

**Comment by T-T-Nguyen** [comment]
Not an issue the past 2 releases
