### ISSUE TITLE
Dashboard French text label typo

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#247]
As per attachment we see SE RENDER it should be SE RENDRE

![Screenshot_20210219-130600__01 (002)](https://user-images.githubusercontent.com/59370759/108729548-a42c2500-74f8-11eb-859c-f0a503143056.jpg)

**Comment by Jiandong-Guo** [comment]
It is same issue as #248, fixed

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Thank you - my browser was having issues and I was uncertain if the ticket was created.

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo This has not been resolved - it still shows up as SE RENDER

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo please reassign this to yourself

**Comment by Jiandong-Guo** [comment]
Hi @T-T-Nguyen ,
Please confirm the label is SE RENDR or SE RENDRE
in ticket#247 is is  SE RENDR, but in ticket#248 it is  SE RENDRE,   it is  SE RENDRE in webapi codebase

**Comment by T-T-Nguyen** [comment]
Hi Jiandong, 

#247 and #248 are the same - I had created them due to a glitch with my browser that day.
