### ISSUE TITLE
Dashboard French label typo

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#248]
@Jiandong-Guo As per attachment we see SE RENDER it should be SE RENDRE

![Screenshot_20210219-130600__01 (002)](https://user-images.githubusercontent.com/59370759/108729548-a42c2500-74f8-11eb-859c-f0a503143056.jpg)

**Comment by Jiandong-Guo** [comment]
It is fixed and ready to test in next release

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Thank you - my browser was having issues and I was uncertain if the ticket was created.
