### ISSUE TITLE
The Eq on Azure VM is crashed.

### ISSUE THREAD

**Issue by Jiandong-Guo** [StatCan/WellbeingCheckUAT#249]
The EQ on Azure VM is crashed after update the webapi.
Please reset it when you get chance.

**Comment by Jiandong-Guo** [comment]
@thierryrama

**Comment by zhuelle** [comment]
@Jiandong-Guo , has the problem resolved and could we close this ticket?

**Comment by zhuelle** [comment]
@Jiandong-Guo could you please comment if we can close this ticket? Thanks!
