### ISSUE TITLE
Memory leaking problem on webapi

### ISSUE THREAD

**Issue by Jiandong-Guo** [StatCan/WellbeingCheckUAT#250]
As talked on our back-forth email, there is a memory leaking problem on our webapi
This is the ticket for tracking

**Comment by Jiandong-Guo** [comment]
@thierryrama

**Comment by zhuelle** [comment]
CMP-29026 This is the ticket created to the CMP project.

**Comment by T-T-Nguyen** [comment]
https://github.com/StatCan/wellBeingCheck/issues/338

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo How can we validate what you released based on @thierryrama 's recommendation in 1.4.27?
