### ISSUE TITLE
Lag when loading survey

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#253]
Several testers indicated that during Beta test there was a substantial lag to load the survey.

@Jiandong-Guo:the main reason is we have to open webview of the phone it makes the process little slow. Another reason is we have to go webapi to get url every time, that is from the original requirement and architecture.  If we can omit this process, may save a little time.   Not sure if it is against security rules. 

Ellen: We cannot omit this process as it is required due to security requirements

**Comment by zhuelle** [comment]
@T-T-Nguyen how we are going forward with this ticket? Based on @Jiandong-Guo's comments, not much can be done by the mobile team.

**Comment by T-T-Nguyen** [comment]
@zhuelle To date, upon moving to the new server I have not received any comments regarding this matter. Should it be required, I will reopen the ticket.
