### ISSUE TITLE
Accessibility: Language Attribute English

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#256]
@Jiandong-Guo The word English for the language toggle also needs to have the language attribute LANg=en in order to satisfy the same accessibility requirement.

**Comment by Jiandong-Guo** [comment]
The Lang attribute is Html staff, not used in react -native,  The sugguest solution is use French in English Env, use Francais in French Env

**Comment by Jiandong-Guo** [comment]
@T-T-Nguyen 
Please check the voice reord(unzip it to your local first)
[Voice_210416.zip](https://github.com/StatCan/WellbeingCheckUAT/files/6326244/Voice_210416.zip)

**Comment by Jiandong-Guo** [comment]
Please test the voice record:
[Voice_210421_1.zip](https://github.com/StatCan/WellbeingCheckUAT/files/6366214/Voice_210421_1.zip)

**Comment by Jiandong-Guo** [comment]
Please check these 2 voice records, one using "Français" in English setting another is using "French"

**Comment by zhuelle** [comment]
@Jiandong-Guo could you please record voice back using your phone and attach it on the ticket when the mobile app page is in French and the ios is in French? In addition, could you please do the same thing for the COVID 19 app if possible? This way, the SMA can listen to compare. Thanks!

**Comment by Jiandong-Guo** [comment]
Please compare the screen reading under english setting and french setting for Covid 19/Wellbeingcheck
[Compare.zip](https://github.com/StatCan/WellbeingCheckUAT/files/6406168/Compare.zip)
Actually, the Covid 19 can switch desktop display name but cannot automatically switch language displaying inside the app, when you change phone language setting.

**Comment by Jiandong-Guo** [comment]
In english setting:  
   for wellbeingcheck:
![1](https://user-images.githubusercontent.com/58485300/116732177-c179e580-a9b8-11eb-940a-e5c925cc3291.jpg)
[1.zip](https://github.com/StatCan/WellbeingCheckUAT/files/6407042/1.zip)
  For Covid19:
[2.zip](https://github.com/StatCan/WellbeingCheckUAT/files/6407050/2.zip)
![2](https://user-images.githubusercontent.com/58485300/116732573-0271fa00-a9b9-11eb-81c6-bf8ed2152f2d.jpg)

**Comment by zhuelle** [comment]
@T-T-Nguyen Jiandong has attached voice back for COVID-19 app and Well-being App in the ticket using his phone. Could you please verify if it is ok after the comparison?

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Ticket will remain open until the new Accessibility assignees complete their testing and provide feedback.
