### ISSUE TITLE
Dashboard Help Button Text Update

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#257]
All   questions about feelings are based on a scale of 0 meaning ‘not at all’, and   10 meaning ’completely’. Based on this, a high rating of feeling happy   compared to a high rating of feeling anxious would be interpreted quite   differently. | Toutes les questions relatives   aux sentiments sont évaluées sur une échelle de 0 à 10, où 0 signifie « pas   du tout » et 10 signifie « complétement ». En fonction de cette échelle, une   cote élevée de sentiment de bonheur par rapport à une cote élevée de sentiment   d’anxiété serait interprétée de manière très différente.
-- | --
  |  
These   results are reported in real time and have not been validated by Statistics   Canada. Caution should be exercised when interpreting the data. | Ces résultats sont communiqués   en temps réel et n’ont pas été validés par Statistique Canada. Il convient   d’être prudent lors de l’interprétation des données.
  |  
Looking   for well-being resources? (The full sentence is displayed as a hyperlink) | Vous cherchez des ressources sur   le bien-être? (The full sentence is to be displayed as a hyperlink)
https://www.statcan.gc.ca/eng/survey/household/5333#a13 | https://www.statcan.gc.ca/fra/enquete/menages/5333#a13

**Comment by Jiandong-Guo** [comment]
@T-T-Nguyen,
How to fix this, the paragraph 1 and 2 is already there, do you want to add paragraph 3 and 4 ? 
also if you want the hyperlink clickable, that will be a big change. cannot be done today

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Yes just 3 & 4

**Comment by Jiandong-Guo** [comment]
Is it clickable or not

**Comment by T-T-Nguyen** [comment]
yes clickable - when can it be done?

**Comment by Jiandong-Guo** [comment]
one week

**Comment by Jiandong-Guo** [comment]
Fixed please test it

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo please modify the text colour for the last line to ensure that the hyperlink is visible. Thank you

**Comment by zhuelle** [comment]
@Jiandong-Guo Could you please look into this ticket ASAP? Thanks!

**Comment by Jiandong-Guo** [comment]
Done

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo on Android the text remains the same colour.

**Comment by Jiandong-Guo** [comment]
Google store cannot update dur to the api version issue. I tried upload so many times, just cannot update.  seems the only choice is to upgeade api.

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Just to be clear:

1. BLUE (HYPERLINK TEXT) - Completed***
Looking for well-being resources? 
Vous cherchez des ressources sur le bien-être? 


2. BLACK/DEFAULT - To be updated***
OK 
D'accord
