### ISSUE TITLE
App Name on Desktop not in French

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#258]
![App Name on Desktop](https://user-images.githubusercontent.com/59370759/114779431-1fb19200-9d44-11eb-807f-435b4a3aef86.jpg)

Hi @Jiandong-Guo,

This is actually something I cannot recall testing when verifying language requirement. Therefore I asked Holly for confirmation,
_that this requirement was identified among all of the discussions of the app being bilingual, and the app content being provided in both languages including the name of the app.  The entire app must be bilingual per the policy on official languages._

**Comment by Jiandong-Guo** [comment]
after did some investigation, and found that the app shortcut name on home is not supported in managed react-native flow(Expo),  also that name must be less than 13 characters.  the better solution is using abbreviation such as Wbc | Bbê

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo The APP name should be in English when settings are in English and the APP name should be in French when settings are in French

English App name: Well-being Check
French App name: Bilan bien-être

Not combined or abbreviated

**Comment by Jiandong-Guo** [comment]
@T-T-Nguyen, It is not possible in our development tool(Expo), because only one name property in configuration(app.json).

**Comment by zhuelle** [comment]
@Jiandong-Guo , could you please do more reasearch on this issue?  I tested and saw that there are other mobile apps can change the name when switching ios between English and French. Is this an official limiation of EXPO? Would it possible to add your reasearch result in the ticket? Thanks!

**Comment by Jiandong-Guo** [comment]
Yes, it is the limitation of Expo.

**Comment by zhuelle** [comment]
@Jiandong-Guo if this is a limitation of Expo, could you please find some official comments from Expo to this ticket?

**Comment by Jiandong-Guo** [comment]
https://forums.expo.io/t/i18n-how-to-localize-the-app-name/13922
https://docs.expo.io/versions/latest/sdk/localization/

**Comment by Jiandong-Guo** [comment]
https://forums.expo.io/t/how-to-localize-app-name-on-android-at-managed-workflow/47944

**Comment by Jiandong-Guo** [comment]
![image](https://user-images.githubusercontent.com/58485300/115975469-f9a1a400-a532-11eb-8be3-1aecf7bef993.png)

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo This can be closed as the solution is to update with a bilingual name
