### ISSUE TITLE
Notification Window Issue

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#260]
@Jiandong-Guo 
The app allows user to set a window shorter than the specs without triggering an error message. 
![Spec_NoError](https://user-images.githubusercontent.com/59370759/115030306-f2c0c480-9e94-11eb-8a74-fc9383559ee9.png)
![Spec_NoError2](https://user-images.githubusercontent.com/59370759/115030365-053afe00-9e95-11eb-8ab0-02185069f292.png)

**Comment by Jiandong-Guo** [comment]
This function was disabled due to it was not working for 0H-24H format, after add new time picker , a new conversion function was added, and enable this line to do the validating work

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Although the error message is triggered, it does not stay on the screen long enough to read and click. Please reassign this back to yourself for review.

**Comment by Jiandong-Guo** [comment]
@T-T-Nguyen ,This popup message will stay there until you click OK button
![image](https://user-images.githubusercontent.com/58485300/115611415-0f576500-a2b8-11eb-8fc9-64bd6e941a7a.png)

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Are you confirming that you modified it and it is now fixed?

**Comment by zhuelle** [comment]
@Jiandong-Guo , I tested on my iphone X and it didn't work. I didn't see the message pop up when I kept the 'do not disturb before and after' the same.

**Comment by zhuelle** [comment]
@Jiandong-Guo I tested again and I think the issue is that there is no pop up triger on the 'do not disturb before'. When I changed the time on the 'do not disturb after' that has the same time as 'do not disturb before', I did see the pop up. However, the pop up was not able to stay on the screen and dissappeared right away. I think this is the error Trish reported and it didn't get fixed.

**Comment by zhuelle** [comment]
@Jiandong-Guo I tested the pop-up is working for android but not for apple .

**Comment by zhuelle** [comment]
@Jiandong-Guo @T-T-Nguyen I tested on my iphone 10 and the pop-up is working now.
