### ISSUE TITLE
Notification issue - JM receipt of two notifications

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#262]
@Jiandong-Guo 
![Two past notifications at the same time](https://user-images.githubusercontent.com/59370759/115031716-7929d600-9e96-11eb-976c-a423dfdd07df.jpg)
After turning off battery saver, user received two past notifications.

**Comment by Jiandong-Guo** [comment]
Please reference to SM Testing: Notifications received at same time #224
