### ISSUE TITLE
Update Name in Google Play and Apple Store

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#264]
@Jiandong-Guo **StatCan Attitude**

**Comment by Jiandong-Guo** [comment]
@T-T-Nguyen Please let me know when the messageResource file and all the screen shot are ready for the new name

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo No they are not, but please proceed with the name change within Google Play and Apple Store.

**Comment by Jiandong-Guo** [comment]
@T-T-Nguyen Please confirm the listing info
### Apple side:

**App name:**   StatCan Attitude

**Promotional Text:**
A Pilot Study on Everyday Well-being conducted on the StatCan Attitude App
Une Étude pilote sur le bien-être quotidien menée sur l’application mobile, StatCan Attitude

**Description:**

Your participation is important
Statistics Canada is currently conducting a pilot study using the StatCan Attitude mobile app that asks Canadians in-the-moment questions about their activities and feelings. The goal is to gain a better understanding of the factors that influence well-being, particularly arts and culture activities, which are the main focus of this pilot. This initiative is in collaboration with Canada Council for the Arts and Canadian Heritage. The data will provide insight on the connections between activities and well-being, and could be used to develop programs that enhance people’s lives.

L’application StatCan Attitude permet de poser des questions sur le vif en vue de mieux comprendre la façon dont les activités quotidiennes contribuent au bien-être global d’une personne. Après avoir configuré l’application, vous recevrez quotidiennement, pendant au maximum 30 jours, des notifications vous invitant à répondre à quelques questions Votre participation est importante

Statistique Canada mène présentement une étude pilote effectuée à partir de l’application mobile StatCan Attitude qui pose des questions sur le vif aux Canadiens au sujet de leurs activités et de leurs sentiments. L’objectif est de mieux comprendre les facteurs qui influent sur le bien-être, en particulier les activités artistiques et culturelles, qui sont au cœur de cette étude pilote. Il s’agit d’une initiative menée en collaboration avec le Conseil des arts du Canada et Patrimoine canadien. Les données fourniront un éclairage sur les liens qui existent entre les activités et le bien-être et elles pourraient servir à élaborer des programmes qui améliorent la vie des gens.

Keywords: bien-être, humeurs, activités, activité, les arts et culture, statistiques, méthode d’échantillonnage de l’expérience, mieux-être, bonheur, sentiments, émotions, joie, Statistique Canada, Patrimoine Canada, Conseil des arts du Canada

**Keyword:**

well-being,activity,arts and culture,statistics,ESM,happiness,emotions,Statistics Canada,Attitude
bien-êtreactivité,arts et culture, statistiques,MEE,bonheur,émotions,Statistique Canada,Attitude


### Google side:
**App name**: StatCan Attitude

**Short description:**
A Pilot Study on Everyday Well-being conducted on the Well-being Check App
Une étude pilote sur le bien-être quotidien menée avec l’appli StatCan Attitude

**Full description:**
Your participation is important
Statistics Canada is currently conducting a pilot study using the Well-being Check mobile app that asks Canadians in-the-moment questions about their activities and feelings. The goal is to gain a better understanding of the factors that influence well-being, particularly arts and culture activities, which are the main focus of this pilot. This initiative is in collaboration with Canada Council for the Arts and Canadian Heritage. The data will provide insight on the connections between activities and well-being, and could be used to develop programs that enhance people’s lives.

Votre participation est importante
Statistique Canada mène présentement une étude pilote effectuée à partir de l’application mobile StatCan Attitude qui pose des questions sur le vif aux Canadiens au sujet de leurs activités et de leurs sentiments. L’objectif est de mieux comprendre les facteurs qui influent sur le bien-être, en particulier les activités artistiques et culturelles, qui sont au cœur de cette étude pilote. Il s’agit d’une initiative menée en collaboration avec le Conseil des arts du Canada et Patrimoine canadien. Les données fourniront un éclairage sur les liens qui existent entre les activités et le bien-être et elles pourraient servir à élaborer des programmes qui améliorent la vie des gens.

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo There seems to be many areas with Well-Being Check in your text above. 
I think instead of moving forward with the app name change as suggested by Ellen last week, I will ask SMA to update the full text in all areas and provide that to you accordingly. If you prefer will keep this open for the time being.

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo 
https://gcdocs.gc.ca/statcan/llisapi.dll?func=ll&objaction=overview&objid=15351226

**Comment by Jiandong-Guo** [comment]
@T-T-Nguyen There are still many "well-being check" in that gcdoc file, is it intentive ?

**Comment by T-T-Nguyen** [comment]
Short description is 80 chars max
Keywords are 100 chars max
Long description is 4000 chars max
Apple side:
App name: StatCan Attitude
Promotional Text:
A Pilot Study on Everyday Well-being conducted on the StatCan Attitude App
Une Étude pilote sur le bien-être quotidien menée sur l’application mobile, StatCan Attitude
Description:
Your participation is important
Statistics Canada is currently conducting a pilot study using the StatCan Attitude mobile app that asks Canadians in-the-moment questions about their activities and feelings. The goal is to gain a better understanding of the factors that influence well-being, particularly arts and culture activities, which are the main focus of this pilot. This initiative is in collaboration with Canada Council for the Arts and Canadian Heritage. The data will provide insight on the connections between activities and well-being, and could be used to develop programs that enhance people’s lives.
Votre participation est importante
Statistique Canada mène présentement une étude pilote effectuée à partir de l’application mobile StatCan Attitude qui pose des questions sur le vif aux Canadiens au sujet de leurs activités et de leurs sentiments. L’objectif est de mieux comprendre les facteurs qui influent sur le bien-être, en particulier les activités artistiques et culturelles, qui sont au cœur de cette étude pilote. Il s’agit d’une initiative menée en collaboration avec le Conseil des arts du Canada et Patrimoine canadien. Les données fourniront un éclairage sur les liens qui existent entre les activités et le bien-être et elles pourraient servir à élaborer des programmes qui améliorent la vie des gens.
Keyword:
well-being,activity,arts and culture,statistics,ESM,happiness,emotions,Statistics Canada,Attitude
bien-êtreactivité,arts et culture, statistiques,MEE,bonheur,émotions,Statistique Canada,Attitude
Google side:
App name: StatCan Attitude
Short description:
A Pilot Study on Everyday Well-being conducted on the StatCan Attitude
Une Étude pilote sur le bien-être quotidien menée avec l’appli StatCan Attitude
Full description:
Your participation is important
Statistics Canada is currently conducting a pilot study using the StatCan Attitude mobile app that asks Canadians in-the-moment questions about their activities and feelings. The goal is to gain a better understanding of the factors that influence well-being, particularly arts and culture activities, which are the main focus of this pilot. This initiative is in collaboration with Canada Council for the Arts and Canadian Heritage. The data will provide insight on the connections between activities and well-being, and could be used to develop programs that enhance people’s lives.
Votre participation est importante
Statistique Canada mène présentement une étude pilote effectuée à partir de l’application mobile StatCan Attitude qui pose des questions sur le vif aux Canadiens au sujet de leurs activités et de leurs sentiments. L’objectif est de mieux comprendre les facteurs qui influent sur le bien-être, en particulier les activités artistiques et culturelles, qui sont au cœur de cette étude pilote. Il s’agit d’une initiative menée en collaboration avec le Conseil des arts du Canada et Patrimoine canadien. Les données fourniront un éclairage sur les liens qui existent entre les activités et le bien-être et elles pourraient servir à élaborer des programmes qui améliorent la vie des gens.

**Comment by Jiandong-Guo** [comment]
Listing text was updated

**Comment by T-T-Nguyen** [comment]
[iOS.zip](https://github.com/StatCan/WellbeingCheckUAT/files/6650794/iOS.zip)
[Android-screenshots.zip](https://github.com/StatCan/WellbeingCheckUAT/files/6650796/Android-screenshots.zip)

**Comment by Jiandong-Guo** [comment]
The screenshots were uploaded

**Comment by T-T-Nguyen** [comment]
[iPad.zip](https://github.com/StatCan/WellbeingCheckUAT/files/6689172/iPad.zip)

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Can you please load the updates to TestFlight as well. No Apple User can see the Listing Details or Images.

**Comment by Jiandong-Guo** [comment]
The testflight doesn't show the listing information, it shows on app store. 
https://developer.a[[le.com/app-store/product-page/ for the layout of the app information on app store.

**Comment by Jiandong-Guo** [comment]
https://developer.apple.com/app-store/product-page/

**Comment by T-T-Nguyen** [comment]
We can only see if we are the developer? A few Apple users indicated that they could not confirm the content update.

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo The content for Apple still needs to be confirmed

**Comment by Jiandong-Guo** [comment]
Even me, I can't see it in testflight, 
How to confirm that ?   1)maybe I open app connect web and let you double check,   2)after in app store, we can check there

**Comment by T-T-Nguyen** [comment]
To review in Prod

**Comment by T-T-Nguyen** [comment]
[Apple.zip](https://github.com/StatCan/WellbeingCheckUAT/files/6711793/Apple.zip)
