### ISSUE TITLE
Review Graph Labels - Task

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#266]
@Jiandong-Guo 
Please ensure that the labels used in the graph matches the updated specifications.

https://gcdocs.gc.ca/statcan/llisapi.dll/open/7291689
Please refer to:

https://jirab.statcan.ca/browse/ICOS-2313
https://jirab.statcan.ca/browse/WBMA20-34

Thank you.

Cc; @thierryrama

**Comment by Jiandong-Guo** [comment]
There is no change on app side, I just tested it by doing a new survey using old use case in browser in QA , the function itself is working, Thierry is checking the graph data is  correct or not.

**Comment by Jiandong-Guo** [comment]
There is no change on app side. it can be close
