### ISSUE TITLE
Dashboard - Vos sentiments display

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#268]
@Jiandong-Guo 
![Dashboard Vos sentiments](https://user-images.githubusercontent.com/59370759/121360901-d1afa980-c902-11eb-80ac-0e0d6de32a21.jpg)

In French, on an android device, for the second dashboard: Vos sentiments : selon l’emplacement  - the help button is displayed very closely to the edge or is sometimes even cut off (depending of the device).

**Comment by T-T-Nguyen** [comment]
Another person:
_The help button is not displayed at all on my screen in French for the last dashboard “Vos sentiments : seul(e) ou avec d’autres”._

**Comment by Jiandong-Guo** [comment]
It's done and will be available to test in next release
