### ISSUE TITLE
Content Update - Extra spaces to be removed

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#269]
@Jiandong-Guo  
Document will be provided

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo 
https://gcdocs.gc.ca/statcan/llisapi.dll/link/15351226

Please note that SMA included the spacing fix for the entire Message Resource so I will close the other ticket.

**Comment by Jiandong-Guo** [comment]
This one is already done, please double check from phone

**Comment by T-T-Nguyen** [comment]
I just added it yesterday, I was not aware that you made an update.

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Could we have an update on this? Thank you

**Comment by Jiandong-Guo** [comment]
It was fixed

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Can you confirm that you reviewed the document provided? SMA said the requests were not applied...

**Comment by Jiandong-Guo** [comment]
@T-T-Nguyen I get that document from gcdoc, Please ask them where to change, don't give me the whole document, I can't  compare the whole document. Thanks

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Please review the track changes within the document

**Comment by Jiandong-Guo** [comment]
The strings in my code are:
"faq.c5.q1": "I cannot access the questionnaires or my results",
            "faq.c5.q1.a": "The questionnaire portal and Results menu require a connection to data or wi-fi to function. If the problem persists after checking your connection, please contact us at ",

            //category5-Question3
            "faq.c5.q2": "I am experiencing other technical difficulties",
            "faq.c5.q2.a": "If you are experiencing display issues, crashes, or other bugs please contact us at ",

            //category5-Question4
            "faq.c5.q3": "Can I download the App on multiple devices and sync it?",
            "faq.c5.q3.a": "The App does not have syncing capabilities.\n\n"+
            "Your participation in the study is based on the device you first downloaded the StatCan Attitude App on. If you download the App on a different device, you will be identified as a new user for security purposes and your previous responses will no longer be accessible to you through the Results menu.",

 //category5-Question1
            "faq.c5.q1": "Je ne peux pas accéder aux questionnaires ou à mes résultats",
            "faq.c5.q1.a": "Le portail du questionnaire et le menu Résultats nécessitent une connexion aux données ou une connexion Wi-Fi pour fonctionner. Si le problème persiste après avoir vérifié votre connexion, veuillez nous contacter au ",

            //category5-Question3
            "faq.c5.q2": "Je rencontre d’autres difficultés techniques",
            "faq.c5.q2.a": "Si vous rencontrez des problèmes d’affichage, des pannes ou d’autres bogues, veuillez nous contacter au ",


The strings in the gcdoc are:
//category5-Question1
            "faq.c5.q1": "I cannot access the questionnaires or my results",
            "faq.c5.q1.a": "The questionnaire portal and Results menu require a connection to data or wi-fi to function. If the problem persists after checking your connection, please contact us at ",

            //category5-Question3
            "faq.c5.q2": "I am experiencing other technical difficulties",
            "faq.c5.q2.a": "If you are experiencing display issues, crashes, or other bugs please contact us at ",

            //category5-Question4
            "faq.c5.q3": "Can I download the App on multiple devices and sync it?",
            "faq.c5.q3.a": "The App does not have syncing capabilities.\n\n"+
            "Your participation in the study is based on the device you first downloaded the StatCan Attitude App on. If you download the App on a different device, you will be identified as a new user for security purposes and your previous responses will no longer be accessible to you through the Results menu.",

//category5-Question1
            "faq.c5.q1": "Je ne peux pas accéder aux questionnaires ou à mes résultats",
            "faq.c5.q1.a": "Le portail du questionnaire et le menu Résultats nécessitent une connexion aux données ou une connexion Wi-Fi pour fonctionner. Si le problème persiste après avoir vérifié votre connexion, veuillez nous contacter au ",

            //category5-Question3
            "faq.c5.q2": "Je rencontre d’autres difficultés techniques",
            "faq.c5.q2.a": "Si vous rencontrez des problèmes d’affichage, des pannes ou d’autres bogues, veuillez nous contacter au ",

            //category5-Question4
            "faq.c5.q3": "Puis-je télécharger l’application sur plusieurs appareils et la synchroniser?",
            "faq.c5.q3.a": "L’application n’a pas de capacités de synchronisation.\n\n"+
            "Votre participation à l’enquête pilote est basée sur l’appareil sur lequel vous avez téléchargé l’application StatCan Attitude pour la première fois. Si vous téléchargez l’application sur un autre appareil, vous serez identifié comme un nouvel utilisateur pour des raisons de sécurité, et vos réponses précédentes ne seront plus accessibles dans le menu Résultats.",


They are same, just mark them with color, or explictly tell me what to change such as change 
"some  space" to
"some space"

**Comment by Jiandong-Guo** [comment]
such as change
"some     space" to
"some space"

**Comment by Jiandong-Guo** [comment]
Can add extra space in github.
use another example:
such as change
"some sp ace" to
"some space"

**Comment by T-T-Nguyen** [comment]
Document will be updated as per request shortly

**Comment by T-T-Nguyen** [comment]
Only pay attention to Patrick Mayrand’s comment. When there was extra spaces to remove, he added a comment and highlighted in yellow. The extra spaces are all before the first word of the paragraphs.
He also added a comment to change the 3 to 4 in both French and English, in the pop up “There needs to be a minimum of 3 hours between .[..]”
There is also a comment about removing a string of numbers in a secret question after the “[...] mother’s name1234 4567?”
StatCan Attitude Wrapper and Notification Text-messageResourceFinal.docx: https://gcdocs.gc.ca/statcan/llisapi.dll/link/15351226
