### ISSUE TITLE
Apple Store Feedback: Guideline 2.1 - Information Needed 

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#271]
@Jiandong-Guo 
Guideline 2.1 - Information Needed

We’re looking forward to completing the review of your app, but we need more information to continue.

Next Steps

Please provide detailed answers to the following questions in your reply to this message in Resolution Center:

- What is the purpose and the main scope of the app? 

Statistics Canada is conducting the Pilot Study on Everyday Well-being to ask Canadians in-the-moment questions about their activities and feelings. The goal is to gain a better understanding of the factors that influence well-being, particularly arts and culture activities, which are the main focus of this pilot. 
The pilot study uses the Experience Sampling Method (ESM)—which measures people’s assessments of their own well-being. Using the StatCan Attitude app, participants will answer a few questions about their well-being several times a day for a 30-day period. This will be the first time Statistics Canada uses the ESM and an app to collect survey data.

- What are the main app features? 
Collecting information using an app to ask in-the-moment questions results in better quality data because it minimizes the need for participants to remember activities after they’ve occurred, lowering the risk that participants misremember details.   
Using an app for the ESM allows for push notifications and the opportunity for participants to see their own data visualized, similar to lifestyle or fitness tracking apps.

- Who is the target audience and how could the users benefit from using the app? 
Anyone in Canada over the age of 15 can choose to download the StatCan Attitude app from GooglePlay or the App Store to participate.
Participants will benefit by receiving their own personalized data tracked by the app and updated as responses are received; this provides a snapshot of participants’ well-being throughout the study.
By participating in this voluntary study, you will join tens of thousands of Canadians who are providing a clearer picture of well-being and the factors that influence it.  

- why you collecting the personal information? What is the purpose of collecting personal information?
From SPIA “Respondents will be asked to complete a short one-time preliminary questionnaire that will collect demographic information that will help Statistics Canada assess what factors could impact well-being.”

The app connects to the secure StatCan collection portal allowing participants who have chosen to download the app on their smartphones to respond to the questionnaire. No questionnaire data is stored on the participant’s smartphone, only in StatCan’s secure infrastructure. There will be no data sharing for this pilot. 
This pilot study fully complies with all accessibility, privacy and security regulations in place to protect Canadians’ information. A Privacy Impact Assessment explaining the security of the app as well as a Supplement to the Generic Privacy Impact Assessment for Statistics Canada explaining the validity of the method will be posted on the StatCan website.

-In addition to personal information, what other information do you collect? 

The Pilot Study on Everyday Well-being asks Canadians questions about their activities and feelings as they are happening, and measures how their well-being is affected by what they are doing, who they are with, and where they are, at that moment.

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Did you get any feedback regarding the screenshots and content?

**Comment by Jiandong-Guo** [comment]
@T-T-Nguyen, Right now I am still waiting for the feedback of the new release which was sent before the new screenhots coming,  Do you want me cancel the current waiting and change the ipad screenshot then a new send review ?

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Sure, lets do that. Thank you!

**Comment by Jiandong-Guo** [comment]
A new review was sent out, keep finger crossed

**Comment by T-T-Nguyen** [comment]
Accepted
