### ISSUE TITLE
Mobile Application Name change

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#272]
@Jiandong-Guo @AJBouzidi **Vitali-T-Stat**

**Comment by Forum-G** [comment]
IOS:
<img width="341" alt="Appname" src="https://user-images.githubusercontent.com/84411852/128775069-2c7d5e0f-6e5a-496f-b9ff-ce805a9d1092.png">
Android:
<img width="325" alt="androidappname" src="https://user-images.githubusercontent.com/84411852/128775075-fe849943-2541-4095-bf35-dbe0a80a3e90.png">

**_AppName Updated and changes are pushed to branch: Forum/MobileAppName._**

**Comment by T-T-Nguyen** [comment]
Thank you!

**Comment by T-T-Nguyen** [comment]
@ForumG-SC @AJBouzidi Please proceed with the name change - "Vitali-T-Stat"

**Comment by T-T-Nguyen** [comment]
StatCan Attitude Wrapper and Notification Text-messageResourceFinal.docx: https://gcdocs.gc.ca/statcan/llisapi.dll/Overview/15351226

Replace all “Statcan Attitude” by “Vitali-T-Stat”

**Comment by Forum-G** [comment]
App Name Updated:
IOS:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/84411852/129604638-60f96db4-5427-4ffa-bcf5-6c8b43d0193f.png">
Android:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/84411852/129604906-e87c88d9-2a28-4f71-ab3c-a68e43aa605e.png">

Changes are pushed to the branch: Forum/MobileAppName

**Comment by AJBouzidi** [comment]
This change has been done, deployed  and will be part of the next release
