### ISSUE TITLE
Dashboard Display Issue

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#273]
@AJBouzidi @Jiandong-Guo 
Navigating in menu affects dashboard title: Issue when navigating to Menu and back to dashboard, while looking at dashboard 2,3 or 4:
When changing by going in the settings while looking at Dashboard 2, 3 or 4, and then pressing “Back” , the title of the dashboard is changed to the dashboard #1 (snapshot), even though you are still on dashboard 2, 3 or 4. The same behaviour is observed in French.

![BEING_ACTIVE1](https://user-images.githubusercontent.com/59370759/129208277-79e731d2-2b6f-4d1c-af58-cf89f3ca710a.png)
![BEING_ACTIVE2](https://user-images.githubusercontent.com/59370759/129208283-d82091c8-63a7-488b-9dcb-c3c9a8666b9e.png)

You can see the title displayed is the one from the first dashboard. That’s because the user went in the setting menu to change language. However, even if you do not change the language, just go in menu, come back, title will swap for the first dashboard.

**Comment by AJBouzidi** [comment]
this done and deployed will be part of the next release
