### ISSUE TITLE
Dashboard 3 - Label Update

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#274]
@AJBouzidi @Jiandong-Guo 
Dashboard 3 labels for cultural events (both language)
Current English: Going to places and Events
New English: Cultural and sporting events
Current French: Se rendre sur les lieux et les évènements
New French: Événements culturels et sportifs 

The label “Being Active” shows up as : BEING_ACTIVE, in both French and English.
Why is this happening?

**Comment by Jiandong-Guo** [comment]
We are missing the translation for BEING_ACTIVE(What we have now is PHYSICAL_ACTIVITY)
please make sure the translation are 
"Being active", "Être actif"

**Comment by Jiandong-Guo** [comment]
Acually the whole dictionary is 
  static Dictionary<string,  Meaning> ResourceDic = new Dictionary<string,  Meaning>
        {
            {"Feelings", new Meaning("Feelings", "Sentiments")}, 
            {"Happy", new Meaning("Happy", "Heureux(se)")}, 
            {"Awake", new Meaning("Focused", "Concentré(e)")},
            {"Relaxed",new Meaning("Relaxed","Détendu(e)")},
            {"InControl",new Meaning("In control of your emotions","En contrôle de vos émotions")},
            {"Anxious",new Meaning("Anxious","Anxieux(se)")},

            {"Feeling Happy",new Meaning("Feeling Happy","Se sentir heureux")},
            {"Feeling Awake", new Meaning("Feeling Awake", "Sentiment d’éveil")}, 
            {"Feeling Relaxed", new Meaning("Feeling Relaxed", "Se sentir détendu")}, 
            {"Feeling InControl", new Meaning("Feeling InControl", "Se sentir en contrôle")}, 
            {"Feeling Anxious", new Meaning("Feeling Anxious", "Sentiment d’anxiété")}, 
            {"Number of times you reported a value less than 4", new Meaning("Number of times you reported a value less than 4:", "Nombre de fois où vous avez signalé une valeur inférieure à 4:")}, 
            {"Number of times you reported a value greater than 7", new Meaning("Number of times you reported a value greater than 7:", "Nombre de fois où vous avez signalé une valeur supérieure à 7:")}, 

            {"Your Feelings with Other People", new Meaning("Your Feelings with Other People", "Vos sentiments avec les autres")}, 
            {"While With Friend", new Meaning("While With Friend", "Avec mes amis")}, 
            {"While Alone", new Meaning("While Alone", "Tout seul")}, 
            {"While With Family", new Meaning("While With Family", "Avec ma famille")}, 
            {"With family", new Meaning("With family", "Avec famille")}, 
            {"With friends", new Meaning("With friends", "Avec des ami(e)s")}, 
            {"While alone", new Meaning("While alone", "Seul(e)")},
            //{"With Others", new Meaning("With Others", "Avec les autres")},
            {"With Pets", new Meaning("With pets", "Avec animaux de compagnie")},
            {"With Colleagues", new Meaning("With Colleagues or classmates", "Avec des collègues ou des camarades de classe")},

            {"Your Weekly Activity Breakdown", new Meaning("Your Weekly Activity Breakdown", "La repartition de vos activités hebdomadaires")}, 
            {"Number of times your selected this activity", new Meaning("Number of times your selected this activity", "Nombre de fois où vous avez sélectionné cette activité")}, 

            {"Your Feelings by Activity Type", new Meaning("Your Feelings by Activity Type", "Vos sentiments par type d’activité")}, 
            {"ActivityType", new Meaning("ActivityType", "Type d'activité")}, 
            {"Average Score", new Meaning("Average rating", "Évaluation moyenne")}, 
            {"Activity", new Meaning("Activity", "Activité")}, 
            {"Location", new Meaning("Location", "Emplacement")}, 
            {"With others", new Meaning("With others", "Avec d’autres personnes")}, 
            {"Your Feelings by Location", new Meaning("Your Feelings by Location", "Vos sentiments selon l’endroit")}, 

             {"Happiness score", new Meaning("Happy", "Heureux(se)")}, 
             {"Relaxed score", new Meaning("Relaxed", "Détendu(e)")}, 
             {"Anxious score", new Meaning("Anxious", "Anxieux(se)")}, 
             {"Awake score", new Meaning("Focused", "Concentré(e)")}, 
             {"In control of emotion score", new Meaning("In control of your emotions", "En contrôle de vos émotions")}, 

            {"Data not found", new Meaning("Data not found", "Données non trouvées")}, 
            {"You have to complete the survey at least once", new Meaning("You have to complete the survey at least once", "Vous devez remplir l'enquête au moins une fois")}, 

            {"WORK_AND_SCHOOL", new Meaning("Work and school", "Travail et études")}, 
            {"PERSONAL_CARE", new Meaning("Personal Care", "Soins personnels")}, 
            {"SOCIAL_ACTIVITIES", new Meaning("Socializing", "Socialisation")}, 
            {"MEDIA_CONSUMPTION", new Meaning("Media Consumption", "Consommation des medias")  }, 
            {"PHYSICAL_ACTIVITY", new Meaning("Being Active", "Être actif")},
            {"BEING_ACTIVE", new Meaning("Being active", "Être actif")},
            {"CHORES", new Meaning("Chores", "Tâches")  }, 
            {"HOBBIES", new Meaning("Creative Hobbies", "Loisirs créatifs")}, 
            {"CULTURAL_AND_SPORTING", new Meaning("Cultural and sporting events", "Se rendre sur les lieux et les évènements")}, 
            {"OTHER", new Meaning("Other activities", "Autres activités")}, 

            {"HOME", new Meaning("At home or own property", "À la maison ou sur la propriété")}, 
            {"WORK_OR_SCHOOL", new Meaning("Work and school", "Travail et études")}, 
            {"SOMEONE_ELSE_HOME", new Meaning("At someone else's home or property", "Chez quelqu’un d’autre")}, 
            {"IN_TRANSIT", new Meaning("In transit", "En transit")}, 
            {"GROCERY_MALL", new Meaning("Grocery store,  other stores or mall", "Épicerie,  autres magasins ou centre commercial")}, 
            {"RESTAURANT_BAR_CLUB", new Meaning("Restaurant,  bar or club", "Restaurant,  bar ou club")}, 
            {"OUTDOORS", new Meaning("Outdoors", "En plein air")}, 
            {"SPORTS_CC_ARENA", new Meaning("Sports centre,  community centre,  field or arena", "Centre sportif,  centre communautaire,  terrain ou aréna")}, 
            {"NEIGHBOURHOOD", new Meaning("In the neighbourhood", "Dans le quartier")}, 
            {"MEDICAL_DENTAL_HEALTH_CLINIC", new Meaning("Medical,  dental or other health clinic", "Clinique médicale,  dentaire ou autre")}, 
            {"PLACE_OF_WORSHIP", new Meaning("Place of worship", "Lieu de culte")}, 
            {"AWAY_FOR_BUSINESS", new Meaning("Away on business", "En voyage d’affaires")}, 
            {"LIBRARY_MUSEUM_THEATER", new Meaning("Library,  museum or theatre", "Bibliothèque,  galerie,  musée ou théâtre")}, 
            {"OTHER_LOCATION", new Meaning("Other location", "Autre endroit")},
            {"WORK", new Meaning("Work", "Travail")},
            {"SCHOOL", new Meaning("School", "École")},
        };
Please double check the Meaning,  format of the Meaning is("English","French"), The Key is the string showing in xml file,  
If you change something, please use color to indicate them so I can know which is changed

**Comment by T-T-Nguyen** [comment]
static Dictionary<string, Meaning> ResourceDic = new Dictionary<string, Meaning>
{
{"Feelings", new Meaning("Feelings", "Sentiments")},
{"Happy", new Meaning("Happy", "Heureux(se)")},
{"Awake", new Meaning("Focused", "Concentré(e)")},
{"Relaxed",new Meaning("Relaxed","Détendu(e)")},
{"InControl",new Meaning("In control of your emotions","En contrôle de vos émotions")},
{"Anxious",new Meaning("Anxious","Anxieux(se)")},
        {"Feeling Happy",new Meaning("Feeling Happy","Se sentir heureux")},

        {"Feeling Awake", new Meaning("Feeling Awake", "Sentiment d’éveil")}, 

        {"Feeling Relaxed", new Meaning("Feeling Relaxed", "Se sentir détendu")}, 

        {"Feeling InControl", new Meaning("Feeling InControl", "Se sentir en contrôle")}, 

        {"Feeling Anxious", new Meaning("Feeling Anxious", "Sentiment d’anxiété")}, 

        {"Number of times you reported a value less than 4", new Meaning("Number of times you reported a value less than 4:", "Nombre de fois où vous avez signalé une valeur inférieure à 4:")}, 

        {"Number of times you reported a value greater than 7", new Meaning("Number of times you reported a value greater than 7:", "Nombre de fois où vous avez signalé une valeur supérieure à 7:")}, 



        {"Your Feelings with Other People", new Meaning("Your Feelings with Other People", "Vos sentiments avec les autres")}, 

        {"While With Friend", new Meaning("While With Friend", "Avec mes amis")}, 

        {"While Alone", new Meaning("While Alone", "Tout seul")}, 

        {"While With Family", new Meaning("While With Family", "Avec ma famille")}, 

        {"With family", new Meaning("With family", "Avec famille")}, 

        {"With friends", new Meaning("With friends", "Avec des ami(e)s")}, 

        {"While alone", new Meaning("While alone", "Seul(e)")},

        //{"With Others", new Meaning("With others", "Avec d’autres personnes")},

        {"With Pets", new Meaning("With pets", "Avec des animaux de compagnie")},

        {"With Colleagues", new Meaning("With colleagues and classmates", "Avec des collègues et camarades de classe")},



        {"Your Weekly Activity Breakdown", new Meaning("Your Weekly Activity Breakdown", "La repartition de vos activités hebdomadaires")}, 

        {"Number of times your selected this activity", new Meaning("Number of times your selected this activity", "Nombre de fois où vous avez sélectionné cette activité")}, 



        {"Your Feelings by Activity Type", new Meaning("Your Feelings by Activity Type", "Vos sentiments par type d’activité")}, 

        {"ActivityType", new Meaning("ActivityType", "Type d'activité")}, 

        {"Average Score", new Meaning("Average rating", "Évaluation moyenne")}, 

        {"Activity", new Meaning("Activity", "Activité")}, 

        {"Location", new Meaning("Location", "Emplacement")}, 

        {"With others", new Meaning("With others", "Avec d’autres personnes")}, 

        {"Your Feelings by Location", new Meaning("Your Feelings by Location", "Vos sentiments selon l’endroit")}, 



         {"Happiness score", new Meaning("Happy", "Heureux(se)")}, 

         {"Relaxed score", new Meaning("Relaxed", "Détendu(e)")}, 

         {"Anxious score", new Meaning("Anxious", "Anxieux(se)")}, 

         {"Awake score", new Meaning("Focused", "Concentré(e)")}, 

         {"In control of emotion score", new Meaning("In control of your emotions", "En contrôle de vos émotions")}, 



        {"Data not found", new Meaning("Data not found", "Données non trouvées")}, 

        {"You have to complete the survey at least once", new Meaning("You have to complete the survey at least once", "Vous devez remplir l'enquête au moins une fois")}, 



        {"WORK_AND_SCHOOL", new Meaning("Work and school", "Travail et études")}, 

        {"PERSONAL_CARE", new Meaning("Personal Care", "Soins personnels")}, 

        {"SOCIAL_ACTIVITIES", new Meaning("Socializing", "Socialisation")}, 

        {"MEDIA_CONSUMPTION", new Meaning("Media Consumption", "Consommation des medias")  }, 

        {"PHYSICAL_ACTIVITY", new Meaning("Being Active", "Être actif")},

        {"BEING_ACTIVE", new Meaning("Being active", "Être actif")},

        {"CHORES", new Meaning("Chores", "Tâches")  }, 

        {"HOBBIES", new Meaning("Creative Hobbies", "Loisirs créatifs")}, 

        {"CULTURAL_AND_SPORTING", new Meaning("Cultural and sporting events", "Événements culturels et sportifs")}, 

        {"OTHER", new Meaning("Other activities", "Autres activités")}, 



        {"HOME", new Meaning("At home or own property", "À la maison ou sur la propriété")}, 

        {"WORK_OR_SCHOOL", new Meaning("Work and school", "Travail et études")}, 

        {"SOMEONE_ELSE_HOME", new Meaning("At someone else's home or property", "Chez quelqu’un d’autre")}, 

        {"IN_TRANSIT", new Meaning("In transit", "En transit")}, 

        {"GROCERY_MALL", new Meaning("Grocery store,  other stores or mall", "Épicerie,  autres magasins ou centre commercial")}, 

        {"RESTAURANT_BAR_CLUB", new Meaning("Restaurant,  bar or club", "Restaurant,  bar ou club")}, 

        {"OUTDOORS", new Meaning("Outdoors", "En plein air")}, 

        {"SPORTS_CC_ARENA", new Meaning("Sports centre,  community centre,  field or arena", "Centre sportif,  centre communautaire,  terrain ou aréna")}, 

        {"NEIGHBOURHOOD", new Meaning("In the neighbourhood", "Dans le quartier")}, 

        {"MEDICAL_DENTAL_HEALTH_CLINIC", new Meaning("Medical,  dental or other health clinic", "Clinique médicale,  dentaire ou autre")}, 

        {"PLACE_OF_WORSHIP", new Meaning("Place of worship", "Lieu de culte")}, 

        {"AWAY_FOR_BUSINESS", new Meaning("Away on business", "En voyage d’affaires")}, 

        {"LIBRARY_MUSEUM_THEATER", new Meaning("Library,  museum or theatre", "Bibliothèque,  galerie,  musée ou théâtre")}, 

        {"OTHER_LOCATION", new Meaning("Other location", "Autre endroit")},

        {"WORK", new Meaning("Work", "Travail")},

        {"SCHOOL", new Meaning("School", "École")},

    };

Pat did some updates and highlighted in yellow. However, he was a bit confused as many lines were repetitive and wasn’t sure exactly where they appeared in the app.

**Comment by T-T-Nguyen** [comment]
Yes, Être actif is the correct translation.

**Comment by AJBouzidi** [comment]
This issue has been fixed and will be deployment in the next release
