### ISSUE TITLE
Dashboard 4 - Label Update

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#275]
@AJBouzidi @Jiandong-Guo 
Dashboard 4 – French label for With others:
Current French label: Avec les autres
Update French label to: Avec d’autres personnes
![Dashboard 4](https://user-images.githubusercontent.com/59370759/129209026-3e56677e-70d8-4118-b62c-bf50c1001d98.png)

Label With pets (both language)
Current English: With Pets
New English: With pets
Current French: Avec animaux domestiques
New French: Avec animaux de compagnie

**Comment by AJBouzidi** [comment]
done
