### ISSUE TITLE
Add Trust Centre Link

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#276]
FYI this will be coming

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo @AJBouzidi 
[Terms and conditions.docx](https://github.com/StatCan/WellbeingCheckUAT/files/7036043/Terms.and.conditions.docx)

Please note that there is a portion in red that has not been updated - English content was shown in the app but French needs to be added.

Changes for the FAQ and T&C


[StatCan Attitude Wrapper and Notification Text-messageResourceFinal.docx](https://github.com/StatCan/WellbeingCheckUAT/files/7041256/StatCan.Attitude.Wrapper.and.Notification.Text-messageResourceFinal.docx)

**Comment by AJBouzidi** [comment]
@T-T-Nguyen do you want  the display of the Trust link will be:  

- (Visit our Trust Centre)  this option the link will be on the text 
- (visit our Trust centre https://www.statcan.gc.ca/trust) this option we add the link after the text.

**Comment by Jiandong-Guo** [comment]
![Screenshot_1629826585](https://user-images.githubusercontent.com/58485300/130664014-c7629112-ea21-4a4d-9e11-aa7d6d7bd21b.png)
Please confirm the url

**Comment by Jiandong-Guo** [comment]
![Screenshot_1629826585](https://user-images.githubusercontent.com/58485300/130664230-4be0cb57-5f32-4ea1-ab75-e009f0442a10.png)

**Comment by Jiandong-Guo** [comment]
![Screenshot_1629826602](https://user-images.githubusercontent.com/58485300/130664379-28c28a80-c859-4a44-a483-2bcd2c8a8744.png)
![Screenshot_1629826668](https://user-images.githubusercontent.com/58485300/130664442-f633d8e9-06a9-49ea-9b93-82f4af451287.png)
![Screenshot_1629826709](https://user-images.githubusercontent.com/58485300/130664490-d13b71dc-7a76-4acd-a620-ab6b7fb719ab.png)

**Comment by T-T-Nguyen** [comment]
https://gcdocs.gc.ca/statcan/llisapi.dll?func=ll&objId=6849080&objAction=browse

**Comment by AJBouzidi** [comment]
English:
https://www.statcan.gc.ca/eng/trust
French:
https://www.statcan.gc.ca/fra/confiance

**Comment by AJBouzidi** [comment]
@T-T-Nguyen @Jiandong-Guo after comparing the 2 files the only changes I saw so far 
Getting Started page in section Session timeout we need to remove 
French :"Après 2 heures d’inactivité, votre session sera interrompue. Vous ne pourrez accéder à aucun renseignement qui n’a pas été sauvegardé. +"
and 
English: "After 2 hours of inactivity, your session will time out. You will not be able to access any unsaved information."

@T-T-Nguyen please ask Patrick to trace his changes.
