### ISSUE TITLE
Blocker - Apple Store and Google Play Screenshots Update

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#277]
@ForumG-SC @Jiandong-Guo @AJBouzidi 
[Android_Aug18.zip](https://github.com/StatCan/WellbeingCheckUAT/files/7014641/Android_Aug18.zip)
[iOS_Aug18.zip](https://github.com/StatCan/WellbeingCheckUAT/files/7014646/iOS_Aug18.zip)
[5.5 iPhone (1242x2208).zip](https://github.com/StatCan/WellbeingCheckUAT/files/7059872/5.5.iPhone.1242x2208.zip)

**Comment by AJBouzidi** [comment]
this is has been update

**Comment by AJBouzidi** [comment]
waiting for comm to give us the latest screenshots.

**Comment by T-T-Nguyen** [comment]
[5.5 iPhone (1242x2208).zip](https://github.com/StatCan/WellbeingCheckUAT/files/7285746/5.5.iPhone.1242x2208.zip)
@AJBouzidi

**Comment by AJBouzidi** [comment]
Apple store has been updated

**Comment by T-T-Nguyen** [comment]
[iPhone- Vitali-t.zip](https://github.com/StatCan/WellbeingCheckUAT/files/7412659/iPhone-.Vitali-t.zip)

**Comment by Forum-G** [comment]
Updated the latest screenshots on Apple Store.

**5.5 inch** screenshots were not the correct size , I resized all the eng and fra screenshots from **1241 x 2208** to **1242 x 2208** .

**Comment by zhuelle** [comment]
@ForumG-SC can we resolve this ticket? My understanding is that Apple has reviewed the current version and it is ready to go production. Thanks!

**Comment by Forum-G** [comment]
> @ForumG-SC can we resolve this ticket? My understanding is that Apple has reviewed the current version and it is ready to go production. Thanks!

Yes, we can close this ticket.
