### ISSUE TITLE
Content Update  - Apple Store and Google Play

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#278]
@Jiandong-Guo @AJBouzidi @ForumG-SC Text in FR and EN for Apple Store and Google Play final.docx - https://gcdocs.gc.ca/statcan/llisapi.dll/link/13719443

**Comment by AJBouzidi** [comment]
This is has been done.

**Comment by T-T-Nguyen** [comment]
@AJBouzidi 

Could you share the content that will be visible in the Apple Store once we move into Production?
