### ISSUE TITLE
Update FAQ: What data does Vitali-T-Stat collect | Quelles sont les données recueillies par l’application Vitali-T-Stat

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#279]
@Jiandong-Guo @AJBouzidi 

StatCan Attitude Wrapper and Notification Text-messageResourceFinal.docx https://gcdocs.gc.ca/statcan/llisapi.dll/link/15351226 

            "faq.c2.q5": "What data does Vitali-T-Stat collect?",
            "faq.c2.q5.a": "The Vitali-T-Stat app helps us collect the responses you provide to questionnaires. The responses collected are transmitted directly to Statistics Canada’s secure Electronic Collection Portal.  No response is stored on your mobile device. This app does not collect data, such as location, from your device."
____

            "faq.c2.q5": "Quelles sont les données recueillies par l’application Vitali-T-Stat?",
            "faq.c2.q5.a": "L’application Vitali-T-Stat nous aide à collecter les réponses que vous fournissez aux questionnaires. Les réponses recueillies sont transmises directement au portail de collecte électronique sécurisé de Statistique Canada. Aucune réponse n’est conservée sur votre appareil mobile. Cette application ne collecte pas de données, telles que votre emplacement, de votre appareil."

**Comment by Forum-G** [comment]
Fixed

**Comment by AJBouzidi** [comment]
this is has been done and released.
