### ISSUE TITLE
Trust Centre URL Update

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#280]
@Jiandong-Guo @AJBouzidi 

CURRENT
To learn more about how Statistics Canada protects your information, visit our Trust Centre.                
Pour savoir comment Statistique Canada protège votre information, consultez le Centre de confiance.

NEW
To learn more about how Statistics Canada protects your information, visit https://statcan.gc.ca/trust.
Pour savoir comment Statistique Canada protège votre information, consultez https://statcan.gc.ca/confiance. 

Please review the updates: The trust centre link was there twice (so 4 times total - 2 English 2 French)

Wrapper text: StatCan Attitude Wrapper and Notification Text-messageResourceFinal.docx https://gcdocs.gc.ca/statcan/llisapi.dll/link/15351226

**Comment by Jiandong-Guo** [comment]
we are not missing urls, Trust Center is displaying text, inside the link are 
https://www.statcan.gc.ca/eng/trust
https://www.statcan.gc.ca/fra/confiance

**Comment by T-T-Nguyen** [comment]
I know, but I'm saying to resolve the fact the the URLs are not being read we will revert to what we had done in the past by providing the full URL for the time being. Unless your team is able to adhere to the accessibility requirements regarding links at this point in time.

**Comment by T-T-Nguyen** [comment]
At least this way, the respondent will be able to know the full url should he/she need to get to it, correct?

Unless you have another solution to propose?

**Comment by AJBouzidi** [comment]
@T-T-Nguyen this is done as expected. 
if you need to run it by accessibility team?
