### ISSUE TITLE
FAQ - Text Error

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#285]
@Jiandong-Guo @AJBouzidi @ForumG-SC 

![Screenshot_20211019-180655_Vitali-T-Stat](https://user-images.githubusercontent.com/59370759/138092014-5041b1bd-1929-4f31-8905-95aa02d1ddc2.jpg)

**Comment by PatMayrand** [comment]
Replicated by 3 android devices so far, when the app is in French.

**Comment by T-T-Nguyen** [comment]
iOS tester also replicated this issue

**Comment by PatMayrand** [comment]
Yes I confirm, we also have an IOS user who replicated the issue.

**Comment by T-T-Nguyen** [comment]
Fixed
