### ISSUE TITLE
High - Release: Move App into Production

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#289]
Please prepare for upcoming release: Scheduled date = November 8th, 2021

**Comment by zhuelle** [comment]
@T-T-Nguyen I would like to clarify the meaning of Schedule date. Do you mean the dev team to push the button on Nov 8 to move the app to Production or the app needs to be searchable or available in app store on Nov 8? Thanks.

**Comment by zhuelle** [comment]
According to Trish, Nov 8th is day that the app requires to be searchable in the store.

**Comment by T-T-Nguyen** [comment]
App in Production
