### ISSUE TITLE
Review Q&A

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#296]
Please review and add comments accordingly - specifically Dark Mode issue and work around.

https://054gc-my.sharepoint.com/:x:/g/personal/julie_goodwin_statcan_gc_ca/EbzgAN3u8bxNmsaanAnCyK4ByTdOYYB-jhXXwgRNwMndXg

**Comment by AJBouzidi** [comment]
@T-T-Nguyen link not accessible. 
for the Darkmode we already find a solution for and we did not deployed. same as other solutions.

**Comment by T-T-Nguyen** [comment]
These will be comments provided to the Respondents should they call our Montreal Help Desk.

Please review and make any updates within the document.

**Comment by T-T-Nguyen** [comment]
@zhuelle Please let me know who will be completing this request. Thank you

**Comment by zhuelle** [comment]
@T-T-Nguyen The link included is not accessible. Would you please update the link?

What is the time line to provide feedback?

**Comment by T-T-Nguyen** [comment]
https://gcdocs.gc.ca/statcan/llisapi.dll?func=ll&objId=18758014&objAction=browse&viewType=1

**Comment by zhuelle** [comment]
@T-T-Nguyen I reviewed the doc and added my comments in some Q&A.
