### ISSUE TITLE
Unable to download app from email link

### ISSUE THREAD

**Issue by almatyssias** [StatCan/WellbeingCheckUAT#297]
**Phone model:** Moto g7 play
**OS Version:** Android V10
**Gmail:** ausernameplz@gmail.com

Successfully followed all steps in the "APK from Google Play Console" section of the wiki. Internal app sharing is turned on.
My issue is in trying to download the application.

Installing android app:
1. Open the Email that send to you on Gmail - Successful
2. Click on the link to open the application in Play store - Successful
3. Install the application if this is the first time if not just click update - **ERROR**

When I attempt to download the application from the "download from Google Play" link, I am redirected to a Google Play store page that simply says "Try Again" with a Try Again Button. Clicking the button yields no results. See the picture below.

![image](https://user-images.githubusercontent.com/35769414/139318096-3982493e-676f-4a8f-a970-da59da369bf1.png)

When I stop the link from redirecting and allow it to open in a browser, I receive the following error message: "We're sorry, the requested URL was not found on this server."

![image](https://user-images.githubusercontent.com/35769414/139317728-f61c43d2-9f0b-4e5e-8794-e1c6e70c1aa4.png)

Extra info + what I've tried:
- I've joined the internal testing team (to prove that see screenshot at the end of the ticket)
- I have done all steps through the Gmail app and attempted to install from/to my phone
- I have had someone send the "download from Google Play" link directly to me to see if we could download it that way
- I have attempted to install the application through a desktop browser to my phone
- I have checked my google account settings, my chrome settings, and my google play settings for anything that might be blocking

As this occurs on both phone and desktop, I'm wondering if there are permissions I'm missing or account settings that must be changed that I am unaware of

![image](https://user-images.githubusercontent.com/35769414/139318173-5eec8e3c-763c-42e0-85fe-3cfc61d5db71.png)

**Comment by zhuelle** [comment]
This is device related issue. The developer has tried to debug this before and it's time consuming.
@ForumG-SC, Please attach the link and let the tester to follow the steps. If it is not working, send APK file to install on the phone.

**Comment by Forum-G** [comment]
Apk link: "76" is the latest version of apk file
https://github.com/StatCan/wellBeingCheck/tree/master/apk

Troubleshooting Steps:
https://support.google.com/googleplay/thread/33393454/google-play-gets-stuck-in-a-blank-page-saying-try-again-upon-opening-app?hl=en

**Comment by T-T-Nguyen** [comment]
@zhuelle Please close ticket
