### ISSUE TITLE
Tester - Unable to download app

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#299]
When user click on the links to download either the testing or the public version to download the App, all he sees is a page asking him to try again (see screenshots)
![GK1](https://user-images.githubusercontent.com/59370759/139482625-d852ff97-6893-48ca-ae75-f76ba3e44744.jpg)
![GK](https://user-images.githubusercontent.com/59370759/139482630-496fbf90-0a8a-4d80-8d79-c36f58c493e6.jpg)
.

**Comment by zhuelle** [comment]
This is device related issue. The developer has tried to debug this before and it's time consuming.
@ForumG-SC, Please attach the link and let the tester to follow the steps. If it is not working, send APK file to install on the phone.

**Comment by Forum-G** [comment]
Apk link: "76" is the latest version of apk file
https://github.com/StatCan/wellBeingCheck/tree/master/apk

Troubleshooting Steps:
https://support.google.com/googleplay/thread/33393454/google-play-gets-stuck-in-a-blank-page-saying-try-again-upon-opening-app?hl=en
