### ISSUE TITLE
Android Tester -  Unable to download app

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#301]
From: JF R <djiefroy@gmail.com> 
Sent: November 1, 2021 10:19 AM
To: Nguyen, Trish - CPRD/DPRC <trish.nguyen@statcan.gc.ca>
Subject: Re: Vitali-T-Stat

Hi,

I am unable to install the app via Google Play through the provided link nor to find it running a search on Google Play itself.

**Comment by T-T-Nguyen** [comment]
Same for kristencouture83@gmail.com

**Comment by zhuelle** [comment]
This is device related issue. The developer has tried to debug this before and it's time consuming.
@ForumG-SC, Please attach the link and let the tester to follow the steps. If it is not working, send APK file to install on the phone.

**Comment by Forum-G** [comment]
Apk link: "76" is the latest version of apk file
https://github.com/StatCan/wellBeingCheck/tree/master/apk

Troubleshooting Steps:
https://support.google.com/googleplay/thread/33393454/google-play-gets-stuck-in-a-blank-page-saying-try-again-upon-opening-app?hl=en

**Comment by T-T-Nguyen** [comment]
Closed - app now in Prod
