### ISSUE TITLE
Android Tester - Unable to download app

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#302]
kristencouture83@gmail.com

**Comment by T-T-Nguyen** [comment]
![KC_Screenshot_20211101-114710_Google Play Store](https://user-images.githubusercontent.com/59370759/139703071-b11230da-67e0-46f7-b7e1-ee6f8c528d3f.jpg)

**Comment by T-T-Nguyen** [comment]
Duplicate

**Comment by zhuelle** [comment]
This is device related issue. The developer has tried to debug this before and it's time consuming. 
@ForumG-SC, Please attach the link and let the tester to follow the steps. If it is not working, send APK file to install on the phone.

**Comment by Forum-G** [comment]
Apk link: "76" is the latest version of apk file
https://github.com/StatCan/wellBeingCheck/tree/master/apk

Troubleshooting Steps:
https://support.google.com/googleplay/thread/33393454/google-play-gets-stuck-in-a-blank-page-saying-try-again-upon-opening-app?hl=en
