### ISSUE TITLE
Details of App Store Content

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#303]
Please provide us with the Apple Store Content.

Thank you.

Trish

**Comment by zhuelle** [comment]
@Jiandong-Guo please take screen shots and attach to this ticket.

**Comment by Jiandong-Guo** [comment]
Descriptions:
Your participation is important
Statistics Canada is currently conducting a pilot study using the Vitali-T-Stat mobile app that asks Canadians in-the-moment questions about their activities and feelings. The goal is to gain a better understanding of the factors that influence well-being, particularly arts and culture activities, which are the main focus of this pilot. This initiative is in collaboration with Canada Council for the Arts and Canadian Heritage. The data will provide insight on the connections between activities and well-being, and could be used to develop programs that enhance people’s lives.


Votre participation est importante
Statistique Canada mène présentement une étude pilote effectuée à partir de l’application mobile Vitali-T-Stat qui pose des questions sur le vif aux Canadiens au sujet de leurs activités et de leurs sentiments. L’objectif est de mieux comprendre les facteurs qui influent sur le bien-être, en particulier les activités artistiques et culturelles, qui sont au cœur de cette étude pilote. Il s’agit d’une initiative menée en collaboration avec le Conseil des arts du Canada et Patrimoine canadien. Les données fourniront un éclairage sur les liens qui existent entre les activités et le bien-être et elles pourraient servir à élaborer des programmes qui améliorent la vie des gens.


ScreenShots:

![2c](https://user-images.githubusercontent.com/58485300/139717968-bf8966bd-d361-4d1a-9acb-9a58f7058e7c.PNG)
![3](https://user-images.githubusercontent.com/58485300/139717972-970691fc-5e9d-4bf1-b71b-6bbebd88b83c.PNG)
![4](https://user-images.githubusercontent.com/58485300/139717973-f147d529-7719-4c3c-b288-7e35739e3786.PNG)
![5](https://user-images.githubusercontent.com/58485300/139717975-04495c99-591b-459b-bd6c-7251a539f4ce.PNG)
![6](https://user-images.githubusercontent.com/58485300/139717977-0349cb3a-b8ed-4cc9-a459-c341b19627eb.PNG)
![7](https://user-images.githubusercontent.com/58485300/139717979-4f6dbcfd-808f-4dbd-8b9a-9a78ed6130d3.PNG)
![8](https://user-images.githubusercontent.com/58485300/139717981-8889180d-6028-4ce8-b134-99a4c179c62d.PNG)
![f1](https://user-images.githubusercontent.com/58485300/139717982-85277c50-c3a7-427a-ab2b-97d9eac080a6.PNG)
![f2](https://user-images.githubusercontent.com/58485300/139717983-37efb0ed-fb1a-49a5-9b81-061766cbc666.PNG)
![f2a](https://user-images.githubusercontent.com/58485300/139717984-e0e34792-4b2e-4a0c-89ec-ec403a3b2721.PNG)
![f2b](https://user-images.githubusercontent.com/58485300/139717987-61b67329-483c-4188-8f2c-570cd7a934df.PNG)
![f2c](https://user-images.githubusercontent.com/58485300/139717989-af70f495-8745-4b1b-9476-2cbcf6866615.PNG)
![f3](https://user-images.githubusercontent.com/58485300/139717991-c8845340-e0f6-4a12-824d-c4f5d06cdf05.PNG)
![f4](https://user-images.githubusercontent.com/58485300/139717993-077d0fe7-d4f9-46ef-a3bc-23d856537041.PNG)
![f5](https://user-images.githubusercontent.com/58485300/139717994-8c15936b-e8cc-4406-8edb-9741efc0eefa.PNG)
![f6](https://user-images.githubusercontent.com/58485300/139717996-42fc6991-40f6-4313-9293-219ce63e966a.PNG)
![f7](https://user-images.githubusercontent.com/58485300/139717999-0ec41173-1c54-4522-a130-efdccb5d5c7a.PNG)
![f8](https://user-images.githubusercontent.com/58485300/139718001-e1b50a62-4e83-40fb-ab35-7d0160da8ecc.PNG)
![1](https://user-images.githubusercontent.com/58485300/139718005-75d6429c-ea38-4801-96c9-8bf9f9c4607f.PNG)
![2](https://user-images.githubusercontent.com/58485300/139718008-a8483348-efe3-4f38-9166-6e99a57a3394.PNG)
![2a](https://user-images.githubusercontent.com/58485300/139718010-b7243f6c-6d38-4ed6-af42-5a973f42d8e9.PNG)
![2b](https://user-images.githubusercontent.com/58485300/139718011-aaec8249-c80b-43ee-a435-1944eb58a83c.PNG)

**Comment by Jiandong-Guo** [comment]
@T-T-Nguyen Please take a loot at the screen shots

**Comment by T-T-Nguyen** [comment]
@Jiandong-Guo Would you actually be able to provide a zip file?

**Comment by Jiandong-Guo** [comment]
[Apple screen shots.zip](https://github.com/StatCan/WellbeingCheckUAT/files/7462997/Apple.screen.shots.zip)
