### ISSUE TITLE
Provide Permission to CPRD to update App Comments/Reviews Section

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#304]
@zhuelle

Put in a place a communication process to respond to any comments/questions/reviews - To be discussed.

**Comment by Forum-G** [comment]
Apple:
https://help.apple.com/app-store-connect/#/devc867852db?sub=dev49ffc6602
https://help.apple.com/app-store-connect/#/deve5f9a89d7?sub=dev49ffc6602

Android:
https://support.google.com/googleplay/android-developer/answer/138230?hl=en#zippy=

**Comment by T-T-Nguyen** [comment]
What information do you require?

**Comment by zhuelle** [comment]
@T-T-Nguyen Have the documents provided in the Forum's comments been reviewed? It provides details to your questions and should be read and understood by the business team if it has not been done.. Based on my reading, 
**For iOS**, the person assigned Customer Support role can analyze and respond to customer reviews on the App Store. If a user has the Customer Support role only, when they click on an app in My Apps, they’ll go straight to the Ratings and Reviews section.
**For Android**, to reply to reviews from Play Console, make sure you have the "Reply to reviews" permission. You can write one public reply for each user review of your app. You can edit your reply to a review at any time.
After you reply to a user’s review, they receive a push notification and an email notification.
Email notifications include the following information:
Name of your app
Date of the user's review
User's rating & review of your app
Your reply
Link to contact you by email (using the contact email address listed on your app’s store listing page)
For best practices on engaging with your users through reviews, visit the Android Developers site.`

**Comment by T-T-Nguyen** [comment]
Yes, I did review the links provided by Forum. 
What I meant was what do you require from us to proceed with the set-up?
Name? Email? Telephone?

**Comment by zhuelle** [comment]
@ForumG-SC , would you please inform Trish how to proceed with the set-up? I would think Name, Email would be required to give proper customer support role. Thanks!

**Comment by Forum-G** [comment]
@T-T-Nguyen For Google Store - Could you please provide me the email address? I would first have to add the person to the store while doing so , I would grant the User feedback permissions which would allow them to respond to the reviews in the store.

For Apple store: Could you please provide me with the First Name, Last Name and Email address ?

**Comment by Forum-G** [comment]
Users have been added to the Google and Apple stores with the permissions.
