### ISSUE TITLE
Apple Store Developer Contact

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#306]
The screenshots Jiandong provided list Ali as the contact
Essentially, what is the purpose of the email?
Who has access to the messages and comments that gets sent to the developer?
Does Apple Store and Google Play store send specific details to the developer via the listed email?
Would it make sense if we were to change it to the infostat email?

**Comment by zhuelle** [comment]
@T-T-Nguyen 
Essentially, what is the purpose of the email? - I believe this email was used when set up the dev account with the store. It is used for app review communication related to development (review, release etc.) The email is not sending to a single person but to the Mobile Application Mail box including all members in the Dev team.
Who has access to the messages and comments that gets sent to the developer? The messages and comments about the app will be managed based on ticket 304. WE need to differentiate App review Vs. Customer review features. 
Does Apple Store and Google Play store send specific details to the developer via the listed email? All messages from Apple and Google regarding development will be sent to Mobile Application mail box
Would it make sense if we were to change it to the infostat email? I don't think so.

**Comment by Forum-G** [comment]
@T-T-Nguyen  Can we close this ticket ?
