### ISSUE TITLE
Keywords Issue

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#309]
well-being,activity,arts and culture,statistics,ESM,happiness,emotions,Statistics Canada,T-Stat
bien-être,activité,arts et culture, statistiques,MEE,bonheur,émotions,Statistique Canada,T-Stat

Is there a reason why some of these keywords are not populating our app, Vitali-T-Stat?

**Comment by Forum-G** [comment]
![image](https://user-images.githubusercontent.com/84411852/140797121-75a20d56-324a-40b2-b973-2341ed4a7686.png)
Reported to the apple store, will let you know once we have any update on it.

**Comment by Forum-G** [comment]
![image](https://user-images.githubusercontent.com/84411852/140948853-32bd4352-cc28-4aa4-b546-3113012c4f46.png)
