### ISSUE TITLE
Provide Data on Downloads - Nov 10th, 2021

### ISSUE THREAD

**Issue by T-T-Nguyen** [StatCan/WellbeingCheckUAT#310]
We would like to know the number of downloads and installation for 1. iOs and 2. Android devices (for public app)

Thank you.

Trish

**Comment by zhuelle** [comment]
@T-T-Nguyen there are 8 downloads for iOS and 0 for Android at the moment.

**Comment by zhuelle** [comment]
@T-T-Nguyen I am wrong for iOS, the downloads is up to Nov 8 not for today. So 0 for today until now

**Comment by T-T-Nguyen** [comment]
Android = 0
iOS = 0

?

**Comment by zhuelle** [comment]
Yes for now.

**Comment by zhuelle** [comment]
Hi @T-T-Nguyen 
I checked downloads this morning:
Android: 66
iOS: 120

**Comment by zhuelle** [comment]
The downloads on Nov 15 @9 am
iOS: 314
Android: 218
